### ISSUE TITLE
Replace _mentionme with _pingme

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-webmention#101]
Right now, the _mentionme parameter gets added identically to the built in _pingme parameter. What if we deprecated _mentionme and used _pingme ? 

If the webmention is successful(and it has a return value, we could check this), then we delete_meta. Otherwise the meta stays and the built-in do_all_pings function will send a pingback?

It seems like it would make it a bit simpler.

**Comment by pfefferle** [comment]
I am not sure if this really helps, because the pingme or mentionme meta key is per post and not per link... so we do not really know if we can remove the pingme flag if one of the links was webmentioned...

**Comment by dshanske** [comment]
You add the URL to pinged and you don't remove the meta value.

**Comment by pfefferle** [comment]
The first point goes to you... But I am still not sure if it helps, to merge both pings... it might end in a racetime condition, if pingbacks are called before the webmentions or something similar...

**Comment by dshanske** [comment]
If Pings get called before Webmentions, Webmentions therefore wouldn't be called.

**Comment by pfefferle** [comment]
But that is not what we want, I think!

**Comment by dshanske** [comment]
But that would only happen if someone deliberately changed it. By default, the webmentions code hooks before the pingbacks code.

**Comment by dshanske** [comment]
Closing this one as it should continue to be separate
