### ISSUE TITLE
Change Comment Flooding Usage in WordPress 4.7

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-webmention#102]
https://core.trac.wordpress.org/ticket/36901

This change in the next version of WordPress should be implemented in the plugin when 4.7 comes to better control comment flooding for webmentions.

**Comment by dshanske** [comment]
Now that 4.7 is out, might quickly add some things.

**Comment by pfefferle** [comment]
perhaps we can remove this completely... It was only added, because Webmention and Semantic Linkbacks both saved a comment in a very short period of time. If we refactor the SL plugin to use the pre save/update hooks, this "hack" seems not needed any more and we can stay with the default behaviour.

**Comment by dshanske** [comment]
We might, but I would still like to return a WP_Error object rather than dying to let the Webmention code determine the return.
