### ISSUE TITLE
Merge Semantic Linkbacks into this plugin

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-webmention#112]
I know there is a reason it was separated, but I want to discuss if that should be revisited.

**Comment by dshanske** [comment]
https://github.com/dshanske/wordpress-webmention/commit/c23c4342defcb2355acf427e2081cdfd2a421405 - The original noted reason for removal of microformats support was the specification. 

The specification now notes that "When a Webmention implementation does support updating (i.e., a "Webmention update implementation"), it MUST support updating data from properties of the primary object of the source. (e.g. properties of the [h-entry] of the page)." This would be an endorsement of microformats within the plugin to a greater degree than now.

The biggest issue is that the php-mf2 parser has a PHP 5.3 dependency. But the plugin could be set to degrade in the event that this occurred. The individual files could be loaded separated. 

I cannot see a scenario where someone would want webmentions and not at least some of Semantic Linkbacks.

**Comment by dshanske** [comment]
As this is a controversial issue, I am expressing a hope for an eventual reunification but accepting that a lot of things that might not be possible at this time would have to be addressed for this to be a reality. I suggest we keep this issue open as a discussion point.

**Comment by dshanske** [comment]
The first question is if separate comment types should be used for like, etc. The comment comment type is the equivalent of reply.

**Comment by tantek** [comment]
TBH I think this is one of the most important improvements to make for the Webmentions plugin. This is key to how Webmentions (as a protocol, web standard, and ecosystem) are so much better designed and implemented than Pingbacks/Trackbacks etc. that the WordPress plugin by the same name should really reflect the full promise of what Webmentions do in practice on the indieweb.

**Comment by gRegorLove** [comment]
Some reasons I think they should be merged:

* Easier setup, fewer steps. "Install this one plugin, then..."
* Nice presentation of webmentions should be a core part of the plugin. Installing the plugin should give the functionality _and_ improved look of comments (vs pingbacks/trackbacks)
* In https://github.com/pfefferle/wordpress-webmention/issues/87#issuecomment-354625216 I realized that some of the data I'm suggesting working with (canonical URL) is provided by Semantic Linkbacks, so would require both plugins. I think canonical URL should be part of the webmention comment meta.
* I don't have a citation handy, but I've seen incidents in #indieweb chat and IndieWebCamps over the years where people are confused by there being two plugins, sometimes installing just Webmention
* The name "Semantic Linkbacks" is jargony, doesn't tell you what it does

**Comment by dshanske** [comment]
@pfefferle and I discussed finally addressing this issue. This will require a new data structure as a first step and a migration function. The brainstorming for this is on the wiki at https://indieweb.org/WordPress/Data

**Comment by snarfed** [comment]
friendly nudge. could be a good project for summit!

**Comment by pfefferle** [comment]
I do not think it is that easy, because I would recommend to rewrite the SL code! The actual version feels really hacky!

**Comment by dshanske** [comment]
@pfefferle Is it better to merge the code and then rewrite, or only incorporate the new non hacky version?

**Comment by pfefferle** [comment]
I would prefer to not merge the code as is, because otherwise it is harder to rewrite it, without the limitations of the old structure...

**Comment by dshanske** [comment]
I will continue with pulling in pieces of infrastructure.

**Comment by snarfed** [comment]
Still seeing confused users file bugs elsewhere due to the bad UX of having these two plugins separate, eg https://github.com/snarfed/bridgy/issues/1355#issuecomment-1330799531. Hope the merge refactoring work is coming along ok!

**Comment by dshanske** [comment]
Resolved via version 5.0.0
