### ISSUE TITLE
<link rel="feed"> in header for Brid.gy (and Instagram)

### ISSUE THREAD

**Issue by chrisaldrich** [pfefferle/wordpress-webmention#116]
I know that about a year ago the plugin began to advertise the webmention endpoint in the header automatically rather than have the user need to add the correct <link> manually.

In the case that one isn't using a theme with really well-formed hfeed, or the site is using a "static page" as the home instead of a "posts page",  one may need to advertise their posts URL so that brid.gy can find it to return replies and likes on some services, and particularly Instagram, which doesn't support rel="me" and in which one doesn't typically include a link back to an original post.

It would be nice if this link were also included automatically based on one's customize.php settings to prevent such potential issues.

The link should generally have the following form:

```HTML
<link rel="feed" type="text/html" title="blog feed" href="http://www.example.com/{POSTS_PAGE_NAME}/" />
```

Thoughts?
 
Cross reference: https://github.com/snarfed/bridgy/issues/718 
https://brid.gy/about#link

**Comment by dshanske** [comment]
The question is...is this a webmention issue or a theme issue?

**Comment by pfefferle** [comment]
...perhaps a feature for https://github.com/dshanske/bridgy-publish

**Comment by chrisaldrich** [comment]
<a href="https://github.com/pfefferle/wordpress-webmention/issues/116#issuecomment-279283619" class="u-in-reply-to"></a>Bridgy won't send webmentions (for Instagram) properly without it, so I'd submit it's more of a webmention issue. It's definitely not a theme issue, and even if it were, only the smallest number of themes would ever be aware to support it anyway. 

Given the broader number of users this could potentially affect, it should be sitting some where towards the top of the stack. I'd recommend webmention first, otherwise, perhaps the IndieWeb Plugin itself?

**Comment by pfefferle** [comment]
@chrisaldrich This is a very specific implementation of Brid.gy and only a fallback if the site does not use `h-feed` or `h-entry` properly, so I think this shouldn't be implemented here. @snarfed why not use `alternate` links instead?

+1 for implementing it into the IndieWeb plugin. @chrisaldrich can you file an issue there?

**Comment by snarfed** [comment]
@pfefferle happy to use rel=alternate links too if they make sense! i followed https://indieweb.org/posse-post-discovery#Algorithm , which only specifies rel=feed right now.

**Comment by pfefferle** [comment]
@snarfed sorry, have to read more carefully! shouldn't write comments so late in the evening. I thought about rss/atom the whole time!

@chrisaldrich sorry, now I fully understand, but I would recommend to implement it in the indieweb plugin anyways, because it is a indieweb specific feature and not part of the webmention spec. Another problem: how to find out the correct URL? is this something a user should know/knows?

**Comment by pfefferle** [comment]
@dshanske where to add this? your bird.gy plugin? the uf2 plugin? the indie web plugin?

**Comment by dshanske** [comment]
I am now implementing rel-feed in my themes if the main feed is not the homepage. I would suggest we close this in favor of that solution.
