### ISSUE TITLE
Possible issue with webmentions and Wordpress (Android) app

### ISSUE THREAD

**Issue by armingrewe** [pfefferle/wordpress-webmention#118]
I'm speculating/guessing at the moment (and as I'm not very technical I have no idea how to dig into this either), but there might be an issue with version 3.0.0 onwards when used together with the Wordpress (Android) app to approve the incoming brid.gy webmentions.

Here's what I'm seeing:
Certainly since today, but possibly since Saturday (when I upgraded to 3.0.0) any webmention I approve with the Wordpress app on Android initially goes through fine, but then disappears (not sure where to and how, they are just gone from the screens I can see and seemingly from my data) when I refresh the comment screen in the app. Any webmention I approve via the web interface remains visible as normal, they are also not impacted by anything I do in the App.

The app (Android version) was last updated on 16/Jan, but I'm only seeing this happening since earliest this weekend. I'm 99% sure I didn't see this happening before, so I don't think it's a problem with the app.

As an immediate measure I've stopped using the app, as the problem doesn't seem to occur in the web interface. However, I would like to use the app when I'm on the move ;-) As I said, unfortunately I'm not very technical, is there anything I can look into to try to understand why this is happening (and if it's related to version 3.0.0+ to help fix it)?

**Comment by dshanske** [comment]
We may have to file a bug against the app itself. Maybe it doesn't respect custom comment types?

**Comment by armingrewe** [comment]
May be I've missed that somewhere, did 3.0.0 introduce a new/different custom comment type? After all I'm only having this problem since 3.0.0, it worked perfectly fine before.

**Comment by dshanske** [comment]
No, it didn't, but you said that the app was recently updated. I don't use the app, but I will try to install and simulate as I am an Android user

**Comment by armingrewe** [comment]
And now it's getting properly weird: When I look it up on my phone as well as tablet it says updated on 16/Jan (and it doesn't show under recently updated apps either, only under up to date apps). That led me to believe it wasn't linked to any changes at the app, as the problem didn't occur between the 16th and today.

However, if I look on the web it says updated 30/Jan (i.e. today). But then I don't recall updating it today. Now I'm properly confused....

**Comment by dshanske** [comment]
Odd... I am thinking possibly a combination of factors. But will try

**Comment by pfefferle** [comment]
Seems really weird, because we only changed the API stuff, not how the comments are stored...

**Comment by dshanske** [comment]
I thought maybe that the app update might have changed how it retrieved it, but then he said it hadn't in fact updated. I am going to install the app, mark a previously approved Webmention as unapproved, then try to approve in app

**Comment by pfefferle** [comment]
is this still a problem?

**Comment by armingrewe** [comment]
Sorry, had forgotten about this. I've stopped using the app for various reasons, so I don't really know. I'd be OK to close this unless someone else who is using the app wants it kept open.
