### ISSUE TITLE
Custom Post Types

### ISSUE THREAD

**Issue by TechLifeWeb** [pfefferle/wordpress-webmention#119]
I'm experimenting with custom post types and they don't seem to be sending webmentions. Regular posts  work just fine. Are custom posts supported? If so, any idea where I should look to see why they aren't sending?

**Comment by dshanske** [comment]
Can you paste your register post type arguments?

**Comment by TechLifeWeb** [comment]
`// Register Custom Post Type
function posse_cpt() {

	$labels = array(
		'name'                  => _x( 'POSSEs', 'Post Type General Name', 'text_domain' ),
		'singular_name'         => _x( 'POSSE', 'Post Type Singular Name', 'text_domain' ),
		'menu_name'             => __( 'Post Types', 'text_domain' ),
		'name_admin_bar'        => __( 'Post Type', 'text_domain' ),
		'archives'              => __( 'Item Archives', 'text_domain' ),
		'attributes'            => __( 'Item Attributes', 'text_domain' ),
		'parent_item_colon'     => __( 'Parent Item:', 'text_domain' ),
		'all_items'             => __( 'All Items', 'text_domain' ),
		'add_new_item'          => __( 'Add New Item', 'text_domain' ),
		'add_new'               => __( 'Add New', 'text_domain' ),
		'new_item'              => __( 'New Item', 'text_domain' ),
		'edit_item'             => __( 'Edit Item', 'text_domain' ),
		'update_item'           => __( 'Update Item', 'text_domain' ),
		'view_item'             => __( 'View Item', 'text_domain' ),
		'view_items'            => __( 'View Items', 'text_domain' ),
		'search_items'          => __( 'Search Item', 'text_domain' ),
		'not_found'             => __( 'Not found', 'text_domain' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'text_domain' ),
		'featured_image'        => __( 'Featured Image', 'text_domain' ),
		'set_featured_image'    => __( 'Set featured image', 'text_domain' ),
		'remove_featured_image' => __( 'Remove featured image', 'text_domain' ),
		'use_featured_image'    => __( 'Use as featured image', 'text_domain' ),
		'insert_into_item'      => __( 'Insert into item', 'text_domain' ),
		'uploaded_to_this_item' => __( 'Uploaded to this item', 'text_domain' ),
		'items_list'            => __( 'Items list', 'text_domain' ),
		'items_list_navigation' => __( 'Items list navigation', 'text_domain' ),
		'filter_items_list'     => __( 'Filter items list', 'text_domain' ),
	);
	$args = array(
		'label'                 => __( 'POSSE', 'text_domain' ),
		'description'           => __( 'For status messages and indieweb POSSE kinds of posts', 'text_domain' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'editor', 'author', 'thumbnail', 'excerpt', 'comments', 'post-formats' ),
		'taxonomies'            => array( 'category', 'post_tag' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,		
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'post',
	);
	register_post_type( 'posse', $args );

}
add_action( 'init', 'posse_cpt', 0 );`

**Comment by dshanske** [comment]
That should work. Hmm...

**Comment by TechLifeWeb** [comment]
Not a huge issue, just testing custom types.

**Comment by TechLifeWeb** [comment]
Not sure if it helps but, I noticed that Trackbacks/Pingbacks are not turned on by default for Custom Post Types. Even though this is the setting I have selected in my settings. I expected custom post types to pick up this setting but it seems mine doesn't.
There is a box to tick when I'm writing the post but that doesn't help. It is only for receiving so you need it ticked to receive a webmention like from Bridgy.
Anyway, Im just posting this in case it helps. If I knew a bit more code, I'd go in and just make sending webmentions the default instead of relying on the switch to see if that works. Or, figure out why the sending is turned off for my custom post type.

**Comment by dshanske** [comment]
Webmentions use the pingback and trackback open setting under Settings->Discussion

https://developer.wordpress.org/reference/functions/get_default_comment_status/ - However, in WordPress 4.3(https://core.trac.wordpress.org/ticket/31168), there was a change to support setting pingbacks to closed except if the custom post type supports trackbacks or if someone sets the filter appropriately. 

It seems the plugin never accounted for this change. You can account for it in your post type by adding 'supports' => array( 'trackbacks' ) to your register_post_type arguments. We should address that by making some other changes, at the least in documentation.

However, that only covers receiving webmentions. Sending them is only governed by the default_pingback_flag which is set under Settings->Discussion

**Comment by TechLifeWeb** [comment]
Settings->Discussion has always been enabled. Thanks for that 'supports' code. Implementing that worked as advertised. I still can't figure out sending. I created 2 test posts to webmentionrocks. One using the usual wordpress Post type and one using my custom post tyeo. Viewing source, they are exactly the same with respect to the header portion. It's like what ever is supposed to trigger the actual sending, doesn't do that.
I am using a child theme of sempress. I could possible have broken something in that but regular posts do send mentions.

**Comment by dshanske** [comment]
I am going to try to add a supports Webmentions feature that can be declared by a custom post type, and dynamically amended for post and optionally page.

**Comment by TechLifeWeb** [comment]
I tried downloading it from here and enabling but it didn't work. I might not be setting it up correctly.
Do I need to add webmentions to the suppors array? for example:
`'supports'              => array( 'title', 'editor', 'author', 'thumbnail', 'excerpt', 'comments', 'post-formats', 'trackbacks', 'webmentions' ),`

**Comment by dshanske** [comment]
Yes. Trackbacks will then be optional.

**Comment by TechLifeWeb** [comment]
Ok. Is it ready for testing yet? Additionally, just to be clear, it is webmentions (with an S)

**Comment by dshanske** [comment]
It is, and is webmentions with an s

**Comment by dshanske** [comment]
Did this work for you? It should make things more clear-cut for the future.

**Comment by TechLifeWeb** [comment]
No, still doesn't work for me. I added webmentions to the supports array and tried sending a web mention to webmention.rocks with no luck.

**Comment by dshanske** [comment]
To an old or new post? You would still have to open up pings on the old post

**Comment by TechLifeWeb** [comment]
No, I created a brand new post.

**Comment by dshanske** [comment]
Interesting. Can you edit the post, and check to see under Discussion if allowing pings/trackbacks is permitted?

**Comment by TechLifeWeb** [comment]
Yes, just checked and they are allowed.

**Comment by dshanske** [comment]
Try a self mention and see if that works please.

**Comment by dshanske** [comment]
Under the previous version, it would not add the trigger for custom post types, let me check that area to see if I missed something as well

**Comment by TechLifeWeb** [comment]
Self mention didnt work either

**Comment by dshanske** [comment]
I tested it using pages as my unsupported type. Going to try to simulate.

**Comment by pfefferle** [comment]
can I close this @dshanske

**Comment by dshanske** [comment]
@TechLifeWeb Still experiencing issues?

**Comment by TechLifeWeb** [comment]
You can close it. I still don't think it it's working but I haven't heard
time to test it.
