### ISSUE TITLE
Translatable API errors?

### ISSUE THREAD

**Issue by pfefferle** [pfefferle/wordpress-webmention#121]
Currently the API error messages are translatable and I am not sure if this is a good idea or if we should remove them and stay with the english versions.

```PHP
return new WP_Error( 'source_url', __( 'Source URL not found', 'webmention' ), array( 'status' => 400 ) );
```

**Comment by dshanske** [comment]
There is both. If there is a consistent error code but different description

**Comment by pfefferle** [comment]
sure, but the error code is not very specific

**Comment by pfefferle** [comment]
sorry, have to read your answers more carefully... do you suggest adding a unique error code?

**Comment by dshanske** [comment]
Basically, what if only part of the message was translatable?

**Comment by pfefferle** [comment]
can you make an example?

**Comment by pfefferle** [comment]
i am so sorry, we already have an error code, but it's not very descriptive in my example... will change some of them before the plugin gets more attention...
