### ISSUE TITLE
url-encode unicode chars in source and target url

### ISSUE THREAD

**Issue by snarfed** [pfefferle/wordpress-webmention#123]
sending a webmention with a unicode char in the source url failed recently, we think because it needs to be url-encoded. basically the same bug as aaronpk/Telegraph#16.

source: https://snarfed.org/2017-02-27_day-69-initial-editing-support-for-quill-100daysofindieweb-•-aaron-parecki 
target: https://aaronparecki.com/2017/02/27/4/day-69-editing-in-quill

the webmention receiver (p3k) responded with HTTP 400 `{ "error": "invalid_request", "error_description": "source or target were invalid" }`: https://telegraph.p3k.io/webmention/11UXLeTChJmz6hXsbk/details

**Comment by pfefferle** [comment]
The plugin send the correct data, so I think it's more a problem of Telegraph, or am I wrong?

ping @aaronpk

**Comment by aaronpk** [comment]
`•` is not a URL-safe character. The plugin should be URL-encoding the `•` for the `source` parameter.
