### ISSUE TITLE
Support fragmentions

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-webmention#125]
http://indieweb.org/fragmention

Proposing specifically that the plugin should support sending and receiving fragmentions. Specifically with receiving, there needs to be a way to identify this in the displayed Webmention.

**Comment by pfefferle** [comment]
from the spec:


> Note that a target URL may contain a fragment identifier, and if the receiver limits which URLs can receive Webmentions, the fragment should be ignored when checking if the URL is supported.

**Comment by pfefferle** [comment]
I am also nut sure what the exact usecase is... do you want to support replies to a specific part in the text?

**Comment by dshanske** [comment]
Yes. I would like to support replies to a specific part in the text.

**Comment by dshanske** [comment]
The above specification excerpt only refers to whether pings are open, not how you address them.

**Comment by chrisaldrich** [comment]
The post at https://kartikprabhu.com/articles/marginalia is an excellent example for sending/receiving fragmentions.

**Comment by pfefferle** [comment]
I had a quick look at the code and saw that we do not strip the fragment part of the URL, so I think the first step is already done.

+1 for closing this issue, because the fragmentation stuff shouldn't be done by the web mention plugin itself.

**Comment by dshanske** [comment]
My plan was to try to simulate this and see if it works without modifications. I will close the ticket if it allows me to send and receive without issue between WordPress sites.

**Comment by pfefferle** [comment]
fair enough!

**Comment by dshanske** [comment]
I did some tests, and there is no way to retrieve the fragment for display purposes, or to check the fragment as part of the dupe. So pull request to address that.

**Comment by pfefferle** [comment]
there is... the target URL is saved with the fragment part, so the function you added can also be done by any third party plugin...

**Comment by dshanske** [comment]
The target URL isn't saved. The PR adds it being saved. If you think it shouldn't check to see if the fragment isn't there in a dupe check, we can adjust.

**Comment by pfefferle** [comment]
it isn't? oh ok... I think you know the code better than me :)

Then forget what I just said and thanks for also fixing the dupes bug!

**Comment by dshanske** [comment]
Well, some of it still surprises me. But remember, I was reading it last night.

**Comment by dshanske** [comment]
After I finish this round, I noticed before I turned it off, Semantic Linkbacks was stripping the fragment, so I intend to chase that down.

**Comment by dshanske** [comment]
Closing due pending PR.
