### ISSUE TITLE
webmentions being interpreted as get rather than post requests

### ISSUE THREAD

**Issue by amandarush** [pfefferle/wordpress-webmention#129]
Webmention receiver is responding to webmention posts by returning the post's HTML itself. Logs: Bridgy: https://brid.gy/log?start_time=1489418712&key=aglzfmJyaWQtZ3lyNQsSCFJlc3BvbnNlIid0YWc6dHdpdHRlci5jb20sMjAxMzo4NDEzMDE2NDUyMDgyMzE5MzcM server access logs for reference in case they're needed: http://www.arush.io/unvarnishedme/2ccff5c840838c30d38416cf4c2530e6/logs/current.log; error logs from the server in case they're needed: https://api.wpengine.com/1.2/?method=errors-site&account_name=unvarnishedme&wpe_apikey=562c98781bc2a4d55c9cd85dfb17742c5c47054e

Specs: WordPress 4.7.3, latest version of stable version of webmention plugin from wordpress.org, plugins recommended by the indieweb plugin are also running.

**Comment by pfefferle** [comment]
@snarfed have you changed something recently? I tested the API endpoint from @amandarush with a post and it returned the correct JSON message.

**Comment by pfefferle** [comment]
I sent the request by hand and (as you can see in your comments) it worked http://www.arush.io/?p=43658

I hope @snarfed can help.

**Comment by amandarush** [comment]
@pfefferle no recent changes, and I see the manual mention.

**Comment by amandarush** [comment]
Submitting a ticket with the host and referencing this issue.

**Comment by amandarush** [comment]
I also attempted to send wms manually based on what Bridgy has collected and although a success message was returned, nothing shows up in either moderation or spam cues. Then uncovered the log showing return of post content with the help of @snarfed.

**Comment by snarfed** [comment]
no recent bridgy changes anywhere near this. lots of debugging details on irc yesterday! https://chat.indieweb.org/2017-03-13

conclusion was that arush's server is responding to bridgy's webmention POST with a 200 and the body of the target page's HTML, which implies that it's badly misconfigured and not interpreting the request as a webmention at all, but as a GET for the target. details in the bridgy log arush posted.

**Comment by amandarush** [comment]
@snarfed thanks for linking the irc log.

**Comment by snarfed** [comment]
one current suspicion is that @amandarush's permalinks have a query param. we wonder if bridgy, the wp plugin, or both aren't url-encoding/decoding or otherwise handling that properly.

**Comment by dshanske** [comment]
I would also try turning off Semantic Linkbacks for debugging. Reduces the possible code to check.

**Comment by pfefferle** [comment]
ok, the encoding might be a indeed a problem. I will release a new version with the en/de-coding, so that we can test it.

**Comment by amandarush** [comment]
The encoding will probably effect some servers, so yeah definitely add it. Also, solved on my end. Endpoint has to be excluded from server-side casching, at least on managed WordPress hosts. So it might be useful to put something about this in the readme.

**Comment by dshanske** [comment]
@amandarush noted she caches her endpoint. This is a note to suggest adding advice to the README that the endpoint be excluded by caching plugins.

**Comment by pfefferle** [comment]
OK, that explains the HTML response!

**Comment by dshanske** [comment]
Is this resolved?

**Comment by pfefferle** [comment]
I will close this for now, feel free to re-open it if you still have problems.
