### ISSUE TITLE
Webmentions stopped working

### ISSUE THREAD

**Issue by sysadmama** [pfefferle/wordpress-webmention#131]
Hi,

I'm using this WordPress/ Indieweb/ brid.gy stuff for month now, but suddenly, all stopped working. All I see is a "FAILED" in brid.gy webinterface when (successfully) retrieving data from Twitter and (unsuccessfully) put it on my blog - and a repeating line in my nginx log:

access.log.1:107.178.195.213 - - [16/Mar/2017:01:47:04 +0100] "POST /wp-json/webmention/1.0/endpoint HTTP/1.1" 400 101 "-" "Bridgy (https://brid.gy/about) AppEngine-Google; (+http://code.google.com/appengine; appid: s~brid-gy)"
access.log.1:107.178.195.214 - - [16/Mar/2017:01:47:07 +0100] "POST /wp-json/webmention/1.0/endpoint HTTP/1.1" 400 101 "-" "Bridgy (https://brid.gy/about) AppEngine-Google; (+http://code.google.com/appengine; appid: s~brid-gy)"
access.log.1:107.178.195.214 - - [16/Mar/2017:01:47:08 +0100] "POST /wp-json/webmention/1.0/endpoint HTTP/1.1" 400 101 "-" "Bridgy (https://brid.gy/about) AppEngine-Google; (+http://code.google.com/appengine; appid: s~brid-gy)"
access.log.1:107.178.195.213 - - [16/Mar/2017:01:47:09 +0100] "POST /wp-json/webmention/1.0/endpoint HTTP/1.1" 400 101 "-" "Bridgy (https://brid.gy/about) AppEngine-Google; (+http://code.google.com/appengine; appid: s~brid-gy)"

Even after googling a lot I have absolutely no clue where to start debugging. Yes, there were WordPress updates in the past, but an error 400 is not enough for me to figure this out. 

Thanks a lot!
  Marianne

**Comment by pfefferle** [comment]
Hallo @sysadmama, is it the unixe.de domain? can you please post me a brid.gy log?

**Comment by sysadmama** [comment]
Hi @pfefferle,

yes I'm talking about that domain :) And of course I'd love to send you logs - if I could find them (<= in CAPS). I feel like I've grep-ed half the internet for this information :( I've found something about a "polling log", but what's the $key?

I'm sorry - usually I'm dot dumb at all.

Thank you!

**Comment by pfefferle** [comment]
Hey @sysadmama no problem ;)

There is a log on the Brid.gy site, when you click on the date. Can you please paste this log as comment?

**Comment by sysadmama** [comment]
Hi @pfefferle,

okay, THAT did the trick - I never had the idea to click on the dates *argh*. I forgot to copy the message, but the problem was: my last published articles did not allow trackbacks AND comments - heaven knows why, I don't. But correcting this was enough, and now my webmentions appear in WordPress again...

Thank you again, your hint pointed me to the right direction :)

**Comment by pfefferle** [comment]
Kein Problem :)
