### ISSUE TITLE
Author ID

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-webmention#135]
Thinking about support for searching the user accounts on the site and setting an author id if the domain name of the post matches the source of the webmention. 

This might combine the identity enhancements in the Indieweb plugin or other plugins to work with user data to generate additional authorship options.

**Comment by pfefferle** [comment]
After thinking about that a lot, I don't think it is a good idea. This change enables external sites to write in your name, if they use the correct `h-card`.

**Comment by dshanske** [comment]
I wonder if there is a way to address that concern.

**Comment by pfefferle** [comment]
Only if we check the rel-me links, but that should be part in the semantic-linkbacks plugin and not part of Webmentions.

**Comment by dshanske** [comment]
Good point

**Comment by dshanske** [comment]
Closing this in favor of a Semantic Linkbacks solution.
