### ISSUE TITLE
Preference Settings - Feature Requests

### ISSUE THREAD

**Issue by dg01d** [pfefferle/wordpress-webmention#137]
It would be great if the webmentions plugin had a configuration pane for a few settings. The two that come to mind immediately on using are:

[x] Radio Button in prefs to remove the public comments widgets from all posts
[x] Facepile for 'like' webmentions

**Comment by pfefferle** [comment]
The comment form can be disabled in the classic WordPress options or what exactly do you mean by "widget"?

**Comment by pfefferle** [comment]
I close this for now, @dg01d please re-open, if you still think this feature is not yet implemented.
