### ISSUE TITLE
HTTP 500 errors and comment_duplicate responses

### ISSUE THREAD

**Issue by gRegorLove** [pfefferle/wordpress-webmention#138]
I've received a couple 500 errors when sending webmentions to WordPress sites. Today I sent:

`source=https%3A%2F%2Fgregorlove.com%2F2017%2F04%2Fawesome-welcome-aboard%2F&target=https%3A%2F%2Fwww.philipbrewer.net%2F2017%2F04%2F07%2Finstalled-webmentions%2F&vouch=http%3A%2F%2Fwww.google.com%2Furl%3Fsa%3Dt%26source%3Dweb%26cd%3D10%26ved%3D0CDoQFjAJahUKEwiwi_ft5O3GAhWJWz4KHfPUCEY%26url%3Dhttp%253A%252F%252Fgregorlove.com%252F2008%252F08%252F888%26rct%3Dj%26q%3Dscavenger%2520hunt%2520downtown%2520indianapolis%26ei%3D2AyvVbC_C4m3-QHzqaOwBA%26usg%3DAFQjCNHLlDEVxH3wPgsDVQlugVOFEkO`

to https://www.philipbrewer.net/wp-json/webmention/1.0/endpoint, receiving a 500 with no response body. I wondered if it was because of the vouch parameter. I realize it could be something else causing it in this instance, but I've also received it before with a duplicate comment response (see below). Later in the day I manually sent this webmention with curl and without the vouch parameter, and got a successful response.

On 2017-02-20, sending:

`source=https%3A%2F%2Fgregorlove.com%2F2017%2F02%2Fstar-commiting-actually-100daysofindieweb%2F&target=https%3A%2F%2Fdavidpeach.co.uk%2F2017%2F02%2F20%2Fday-1-commiting-actually-100daysofindieweb&vouch=https%3A%2F%2Fgithub.com%2FgRegorLove`

to https://davidpeach.co.uk/wp-json/webmention/1.0/endpoint with response:

`{"errors":{"comment_duplicate":["Duplicate comment detected; it looks as though you&#8217;ve already said that!"]},"error_data":{"comment_duplicate":409}}`

**Comment by gRegorLove** [comment]
Just had another one of these without vouch parameter, so it's probably not that:

`curl -i -d source=https://gregorlove.com/2017/04/woot/ -d target=https://doubleloop.net/2017/04/08/149/ https://doubleloop.net/wp-json/webmention/1.0/endpoint`

```
HTTP/1.1 500 Internal Server Error
Date: Sat, 08 Apr 2017 20:03:27 GMT
Server: Apache/2.4.18 (Ubuntu)
X-Robots-Tag: noindex
Link: <https://doubleloop.net/wp-json/>; rel="https://api.w.org/"
X-Content-Type-Options: nosniff
Access-Control-Expose-Headers: X-WP-Total, X-WP-TotalPages
Access-Control-Allow-Headers: Authorization, Content-Type
Allow: POST, GET
Content-Length: 554
Connection: close
Content-Type: application/json; charset=UTF-8

<br />
<b>Notice</b>:  Array to string conversion in <b>/var/www/doubleloop.net/public_html/wp-content/plugins/semantic-linkbacks/includes/class-linkbacks-mf2-handler.php</b> on line <b>421</b><br />
<br />
<b>Notice</b>:  Array to string conversion in <b>/var/www/doubleloop.net/public_html/wp-content/plugins/semantic-linkbacks/includes/class-linkbacks-mf2-handler.php</b> on line <b>421</b><br />
{"errors":{"comment_duplicate":["Duplicate comment detected; it looks as though you&#8217;ve already said that!"]},"error_data":{"comment_duplicate":409}}
```

**Comment by pfefferle** [comment]
Have you enabled "frontpage" webmentions?

**Comment by gRegorLove** [comment]
@pfefferle I'm not running WordPress; these are errors I get when sending to WordPress sites.
