### ISSUE TITLE
Get "publicly_queryable" post_types, not just "public" ones

### ISSUE THREAD

**Issue by singpolyma** [pfefferle/wordpress-webmention#139]
Just because I don't want my post type in my nav, doesn't mean it's not public enough that I want to send webmentions!

**Comment by dshanske** [comment]
This was already changed in the development version to have the custom post type declare Webmention support

**Comment by dshanske** [comment]
I think this can be closed

**Comment by pfefferle** [comment]
sure!

@singpolyma please re-open if you still have problems.
