### ISSUE TITLE
`admin_register_settings` is not working

### ISSUE THREAD

**Issue by pfefferle** [pfefferle/wordpress-webmention#140]
@dshanske can you please fix `admin_register_settings`.

I am getting notices in the admin backend:

```
Notice: Undefined offset: 0 in /var/www/html/wp-includes/plugin.php on line 999

Notice: Undefined offset: 0 in /var/www/html/wp-includes/plugin.php on line 981

Notice: Undefined offset: 0 in /var/www/html/wp-includes/plugin.php on line 999

Notice: Undefined offset: 0 in /var/www/html/wp-includes/plugin.php on line 981

Notice: Undefined offset: 0 in /var/www/html/wp-includes/plugin.php on line 999
```

The doku says the third param of the `register_setting` should be a callback, but its an args array instead.

**Comment by dshanske** [comment]
https://developer.wordpress.org/reference/functions/register_setting/ 

It was a callback...it is now an array.

**Comment by dshanske** [comment]
Either way, that error suggests an action or a filter was improperly called. Having a look.

**Comment by dshanske** [comment]
Is there anything more in the log?

**Comment by pfefferle** [comment]
you are right, the problem is in the template... after you have added the register settings, all settings are under the discussion option. `get_option("webmention_*")` has to be replaced with `get_option("discussion")[webmention_*]`.

**Comment by dshanske** [comment]
https://developer.wordpress.org/reference/functions/get_option/

Doesn't seem to note that the area is required.

**Comment by pfefferle** [comment]
ok, this was only a guess... do you have an idea or can you reproduce it?

**Comment by dshanske** [comment]
I can't, but haven't given up

**Comment by pfefferle** [comment]
seems to be a problem with WordPress < 4.7.x, sorry!
