### ISSUE TITLE
500 error with semantic-linkbacks on reply webmention from bridgy

### ISSUE THREAD

**Issue by snarfed** [pfefferle/wordpress-webmention#141]
i'm getting a consistent 500 for a reply webmention from https://brid-gy.appspot.com/comment/twitter/schnarfed/864852973393805313/864855688404647936 to https://snarfed.org/2017-05-17_24262. 

[here's the full HTTP response body](https://github.com/pfefferle/wordpress-webmention/files/1011708/err.html.txt) (it doesn't have anything interesting). i've set `WP_DEBUG*` to true and PHP's `display_errors` and `log_errors` on, but i still don't get a stack trace or any warning, error, or fatal log messages in either apache's error log or wordpress's debug log. i can reproduce it locally, though, so i'm happy to try other things to help debug, just let me know what!

i'm on wordpress 4.7.5, webmention 3.1.1, and semantic-linkbacks 3.3.0. i haven't overridden the `webmention_post_id` filter. i'm not yet sure if the root cause is in webmention or SL; i'm happy to move this to a SL issue if we want.

[IRC](https://chat.indieweb.org/dev/2017-05-17#t1495046167145000), [more](https://chat.indieweb.org/dev/2017-05-18#t1495125731348000). similar symptom to #138, but probably not the same bug, since that one reports a duplicate comment error, and this doesn't.

**Comment by pfefferle** [comment]
oh, you have some really strange effects with some specific plugin! Try send a webmention with https://snarfed.org/wp-json/webmention/1.0/endpoint and you get an error:

```
Notice: It seems you have Javascript disabled in your Browser. In order to submit a comment to this post, please write the code below the form along with your comment.
```

and this seems to be a message of https://de.wordpress.org/plugins/stop-spam-comments/

**Comment by snarfed** [comment]
huh, true, thanks for the catch! interesting, i've had that plugin installed for a long time, and iirc it hasn't caused this problem before. also other webmention mf2 types, e.g. likes, are coming through ok.

regardless, good point, this is probably specific to my setup. i'll debug more and update or close this issue soon.

**Comment by pfefferle** [comment]
can you try to reproduce this error with wordpress-webmention 3.3.0

**Comment by snarfed** [comment]
thanks for checking! same problem happens with 3.3.0.

**Comment by snarfed** [comment]
i'm debugging this more now. if i deactivate the JS Stop Spam Comments plugin, the same webmention(s) succeed, so it definitely is the problem. i'll try to figure out why and send a PR.

**Comment by pfefferle** [comment]
Any news on this?

**Comment by snarfed** [comment]
hey, thanks for the nudge! totally forgot about this one. i ended up turning off the Stop Spam Comments plugin.

i tested just now, and sending that original webmention works with Stop Spam Comments both on and off. woo!
