### ISSUE TITLE
Webmention Form not showing

### ISSUE THREAD

**Issue by chrisaldrich** [pfefferle/wordpress-webmention#143]
A while back @pfefferle's [webmention form](https://github.com/pfefferle/wordpress-webmention-form) was rolled up into the main Webmention plugin. I've heard that altplatform.org added the current Webmention plugin and has the checkbox for "Show a Webmention form at the comment section, to enable manual pings." yet the form isn't showing up in their comments section.

Is anyone else seeing this behavior on their end? (The settings are under "Settings>Discussion" at /wp-admin/options-discussion.php)

Incidentally, I've still got the old-school GH stand-alone version installed and it doesn't cause a conflict (or duplicate that form), but when I disable the stand-alone version, the webmention form disappears, so it seems to be a bug of some sort.

**Comment by dshanske** [comment]
I have the plugin on two sites and both show/hide it per the setting

**Comment by pfefferle** [comment]
do you use any kind of caching mechanism?

**Comment by chrisaldrich** [comment]
<a href="https://github.com/pfefferle/wordpress-webmention/issues/143#issuecomment-308404963" class="u-in-reply-to"></a>To my knowledge they don't. I do and turned mine off when I tested it on my site to see the same result.

I did spin up a fresh site this morning to test against that and didn't see the same issue. Perhaps it's something theme or CSS specific? Let me try some more tests this afternoon.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/pfefferle/wordpress-webmention/issues/143" class="u-in-reply-to"></a>I'll check to see if it's the case with altplatforms' bug, but I've discovered that it's having Jetpack's commenting feature "Let readers use WordPress.com, Twitter, Facebook, or Google+ accounts to comment" activated that prevents the Webmention Form from appearing on the page. If I deactivate it, it not only appears properly, but shows up twice with the standalone plugin installed.

Incidentally it also causes issues on my 2016 theme where if one types too much in the enclosed field, the UI moves down and it becomes impossible to actually post the comment!

While I'm thinking about it, as an Indieweb-forward thought, would it be possible to put the Webmention Form at the top of the comment section instead of underneath it? While I'm (and I'm sure most of us are) receptive to comments in general, it would be nice to encourage others to own theirs at the top and then provide the default comment form underneath it. Just a thought...

I'll do some additional testing and report the bug to JetPack shortly.

**Comment by kraftbj** [comment]
Apologies on our (Jetpack's) end for this. Since we take over comment submission on sites using our comment form, we `remove_all_actions` for both before and after the contact form. It's been a solid five or six years since that decision was made and I haven't looked back through our p2 posts to see if there's any particular reason for that, short of trying to avoid obvious conflicts by removing anything that might.

I can't comment what we'll opt to do in the end, but thanks for bringing this to our attention.

**Comment by dshanske** [comment]
@kraftbj Glad to see interest from the Jetpack community. But, what about a jetpack specific hook, which would ensure that anyone using it would know what they were doing?

**Comment by dshanske** [comment]
I think this was fixed on the jetpack end

**Comment by kraftbj** [comment]
Yup, fixed in https://github.com/Automattic/jetpack/pull/7358

**Comment by pfefferle** [comment]
Nice, thanks @kraftbj
