### ISSUE TITLE
Endpoint advertised on homepage even if not accepted

### ISSUE THREAD

**Issue by colin-walker** [pfefferle/wordpress-webmention#152]
Now that options exist to enable/disable webmentions on the homepage should the endpoint no longer be advertised on the home page/other pages that don't accept webmentions?

**Comment by dshanske** [comment]
We tried that. There were issues and it was reverted.

**Comment by colin-walker** [comment]
Fair enough, it was just a thought.

**Comment by dshanske** [comment]
I am not closing it as an issue. Just mentioning the challenge

**Comment by dshanske** [comment]
I can't remember what the problem was. Thinking of bringing back this feature and it could be disabled.

**Comment by dshanske** [comment]
Related #75

**Comment by dshanske** [comment]
Addressed now
