### ISSUE TITLE
Does it display well with Disqus?

### ISSUE THREAD

**Issue by renettarenula** [pfefferle/wordpress-webmention#155]
Tried out this plugin by linking to my post on another post. It seems to appear on the comment dashboard but it doesn't appear on my post's comment section. I wonder if it is because I am using Disqus? It doesn't integrate well with Disqus plugin, does it?

**Comment by pfefferle** [comment]
Webmentions are only working with the native comment system of WordPress. Disqus is completely replacing the comment part, so you will receive webmentions, but they will not be displayed.

**Comment by pfefferle** [comment]
It is similar to this btw. https://github.com/pfefferle/wordpress-webmention/issues/143

**Comment by pfefferle** [comment]
I would recommend to you to disable disqus in favor of the native comment system and web mentions/trackbacks/pingbacks.

**Comment by renettarenula** [comment]
@pfefferle I see. Thanks for replying. I'm not expecting for a fix, just a general question :)
I love web mentions and Disqus but it seems that we can't integrate it together on WordPress.
