### ISSUE TITLE
Empty comment from manual ping

### ISSUE THREAD

**Issue by jackysee** [pfefferle/wordpress-webmention#157]
Try to do a manual ping, where the source page is as simple as
```
<html>
<body><a href="http://link-to-target-article">Link to article</a></body>
</html>
```
The ping return success json:
```
{"link":"\/comment-page-72\/#comment-202993"
,"source":"http:\/\/link-to-source"
,"target":"https:\/\/link-to-target-article"
,"code":"success"
,"message":"Webmention was successful"}
```
A comment is created in wordpress, but all the fields (name, email, url, comment) and webmention datas are empty.

Should this case be rejected?

**Comment by pfefferle** [comment]
Hmmm, good question...

Per definition your example is a valid Webmention and the author parser is by definition very simple: https://github.com/pfefferle/wordpress-webmention/blob/master/includes/class-webmention-receiver.php#L544

Any ideas @dshanske @snarfed ?

**Comment by snarfed** [comment]
sorry, no, no obvious ideas here.

**Comment by tw2113** [comment]
Potentially a bit late, but I think this one is simply a case of there's nothing for the receiver to parse and populate the mention with. It finds what it can, but it's really darn sparse. Still worth keeping open if someone wants to poke at it a bit more.
