### ISSUE TITLE
Fatal Error with WP_Error as array in Webmention Form

### ISSUE THREAD

**Issue by chrisaldrich** [pfefferle/wordpress-webmention#165]
As mentioned in [IW chat](https://chat.indieweb.org/2018-03-27#t1522150366409300):

When placing the URL <https://abraham.uno/909/listening-an-indieweb-podcast-episode-0/> into the Webmention Form at <http://boffosocko.com/2018/03/19/an-indieweb-podcast-episode-0-considering-the-user/#Respond+on+your+own> the following Fatal Error appears at <http://boffosocko.com/wp-json/webmention/1.0/endpoint>:

`Fatal error: Uncaught Error: Cannot use object of type WP_Error as array in /htdocs/wp-content/plugins/webmention/templates/webmention-api-message.php:119 Stack trace: #0 /htdocs/wp-content/plugins/webmention/includes/class-webmention-receiver.php(161): require_once() #1 /htdocs/wp-includes/class-wp-hook.php(298): Webmention_Receiver::serve_request(false, Object(WP_REST_Response), Object(WP_REST_Request), Object(WP_REST_Server)) #2 htdocs/wp-includes/plugin.php(203): WP_Hook->apply_filters(false, Array) #3 /htdocs/wp-includes/rest-api/class-wp-rest-server.php(380): apply_filters('rest_pre_serve_...', false, Object(WP_REST_Response), Object(WP_REST_Request), Object(WP_REST_Server)) #4 /htdocs/wp-includes/rest-api.php(271): WP_REST_Server->serve_request('/webmention/1.0...') #5 /htdocs/wp- in /htdocs/wp-content/plugins/webmention/templates/webmention-api-message.php on line 119`

(Originally published at: http://boffosocko.com/2018/03/27/issue-fatal-error-with-wp_error-as-array-in-webmention-form/)

**Comment by pfefferle** [comment]
Have you installed the Webmention forms plugin? Or only the Webmentions plugin?

**Comment by chrisaldrich** [comment]
You may recall that I used to have the Webmention Forms plugin separately. But now I'm relying solely on the Webmentions Plugin by itself now that the functionality has been bundled into one plugin.
