### ISSUE TITLE
Anonymize IP Address

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-webmention#172]
I cannot think of a reason why we need the originating IP address after any sort of SPAM check is done. We could safely anonymize this information after that time.

**Comment by pfefferle** [comment]
Perhaps we can remove it within the publish process...

**Comment by dshanske** [comment]
I want to make sure there isn't a spam fighting reason for retaining it longer

**Comment by dshanske** [comment]
https://github.com/WordPress/WordPress/blob/fdd5b8dacdf5f3e107747e9870c2f2db3f3481b1/wp-includes/functions.php#L6143 

https://github.com/WordPress/WordPress/blob/fdd5b8dacdf5f3e107747e9870c2f2db3f3481b1/wp-includes/functions.php#L6212

**Comment by tw2113** [comment]
Not sure if everyone would want to consider some sort of basic cron job to clear out IP addresses tied to webmention comments, but it's an option.
