### ISSUE TITLE
Change wording of send a url for webmention box

### ISSUE THREAD

**Issue by jgmac1106** [pfefferle/wordpress-webmention#174]
I see a lot of confusion around the webmention-form. There are three situations.

- Someone with webmentions plug in installed who just wrote a post but didn't add response  properties (probably because it is behind screen options rather than default)
- Someone with webmentions installed who correctly adds response properties but also thinks they still need to copy and paste link (has to approach 40-50%).
- Someone without webmentions installed.

I suggest the following wording:
`
<p> If you would like to send  a <a  href=“new gen3 page”>webmention</a> to me but do not have an IndieWeb powered site you still can. Write and post something on your blog, website, or social media. Then paste the link below. Your webmention will show up as a comment. </p><p> Want to update or remove your webmention? First Update or delete your post. Then repost the link below. To learn how to bring the indieweb to your blog check out this site “#"</p><p>Already have webmentions on your blog? Awesome just link back to this post and you are down.</p>`

**Comment by jgmac1106** [comment]
Though it is only a lesson one needs to learn once or twice so not a critical bug at all.

**Comment by dshanske** [comment]
Response properties have nothing to do with webmentions, but I think maybe that is a bit long unless it is behind a link

**Comment by jgmac1106** [comment]
@dshanske What I meant by response properties is somebody may think they are correctly sending a webmention but they are not entering the target url because they did not enable response properties in screen options.

**Comment by pfefferle** [comment]
Is this still an issue, now that you can edit the text?

**Comment by jgmac1106** [comment]
No
