### ISSUE TITLE
Make the webmention form text editable

### ISSUE THREAD

**Issue by jgmac1106** [pfefferle/wordpress-webmention#175]
@pfefferle  Has a good description for his audience. 

I work with audiences that do not know what half of the words in his description and would also like to evangelize so I like something like #174.  

Yet if Matthias used half the language I used he would get hate mentions from the web explaining what is wrong in his description.

We should be able to change the text.

**Comment by dshanske** [comment]
You can as a filter. I suppose it could be a setting
