### ISSUE TITLE
pfefferle/wordpress-webmention: display webmentions in admin log widget

### ISSUE THREAD

**Issue by dougbeal** [pfefferle/wordpress-webmention#187]
Right now its extremely difficult to debug outgoing webmentions, and incomming webmentions are hard.  A admin widget that displayed a log of webmentions would simplify debugging greatly.  It should capture incomming and outgoing webmentions (and looking to the future salmentions, vouches).

(Originally published at: https://crw.moe/b/bb)

**Comment by tw2113** [comment]
Related https://github.com/pfefferle/wordpress-webmention/issues/147
