### ISSUE TITLE
Webmention (reply) sent too soon?

### ISSUE THREAD

**Issue by metbril** [pfefferle/wordpress-webmention#189]
I manually created a 'reply' to aaronpk's website from the  dashboard. After saving it, I checked to page I replied to and that immediately showed my mention.

However, it showed the post slug as a link back to my own post and NOT the reply I had typed into the note field.

I copied my permalink and pasted it back in the originating page, and then the mention was updated with the actual content of my reply.

This looks like the webmention is being sent a little too early?

**Comment by pfefferle** [comment]
how can they be sent too early? You hit save and then they will be sent. The process is to that async and will be triggered from a WP_Cron. Can you give a bit more details? Perhaps with the code of the original post, and how the post on the other page looked in the first place?

**Comment by metbril** [comment]
To reproduce:

I have sent another reply to the same post and uploaded some screenshots

- Copy link from post to reply to: https://aaronparecki.com/2018/08/19/24/
- Go to WP editor https://example.org/path-to-wordpress/wp-admin/post-new.php
- Pick post kind 'reply'. The Response Properties pane will show.
- Pick post type 'link'.
- Paste in Response Properties URL. Response Properties Details will be fetched.
- Enter reply in editor. (For this one I entered "`Nice! `")
- Hit **Publish** button.
- Click the **View message** link.
- Copy your own permalink to the clipboard
- Click the link to the original post. Refresh page until mention shows:

![afbeelding](https://user-images.githubusercontent.com/559346/44327607-62215480-a45f-11e8-98f6-6f2be4fa46d8.png)

- Paste your own permalink in the webmention box and hit 'Send Webmention'
- Refresh the page and notice your mention being updated.

Please note: I noticed that using 'link' instead of 'standard' makes a difference.

![afbeelding](https://user-images.githubusercontent.com/559346/44328030-c1cc2f80-a460-11e8-936c-7e386afca406.png)

**Comment by pfefferle** [comment]
Ah, you are using the post-kinds plugin... I am not sure, what post-kinds is doing after saving a post, so perhaps @dshanske can help?!? Seems to be no general problem, but a problem of the combination of both plugins.

**Comment by pfefferle** [comment]
Yes, the post-kinds plugin has some glitches and a standard article has no reply-context forms, but shows them accidently in some special cases... So, can you re-try it with a "reply" kind and see if it works?

**Comment by dshanske** [comment]
That's it, if Post Kinds are enabled I am disabling post formats. It is just confusing people

**Comment by metbril** [comment]
@dshanske 

> I am disabling post formats

I hope you mean 'hiding' by 'disabling'. The use of post formats (like Standard, Aside, etc.) is required for use in most templates, since it's one of the corner stones of templating.

Another approach (if even feasible) is to map post kinds to their best matching post format and then automatically change the post format based on the selected post kind.

For example:

article -> Standard
note -> Aside
reply, repost, bookmark, like, favourite -> Link
photo -> Image
video -> Video
etc.

**Comment by pfefferle** [comment]
You mentioned some switchings between "standard" and "link"...

But nevertheless, it seems to be more of a post-kinds problem and not a webmention problem?!?

/cc @dshanske

**Comment by pfefferle** [comment]
Oh no, it is a SemPress issue! If you are using the Standard post format, SemPress adds a header if you use link, SemPress adds no header...

@aaronpk do you use `p-name` for reactions?!?

**Comment by dshanske** [comment]
Post Kinds already sets post formats in the background.

**Comment by metbril** [comment]
I don't see the post format changing on the fly when I change the post kind. So (I think) I need to be careful to pick the best suiting post format myself.

**Comment by dshanske** [comment]
It only changes on initial set, changing on a change once created is not yet implemented.

**Comment by metbril** [comment]
I like discussing this, but this repo and issue is not the right place. Wouldn't the Wordpress chat be a better location?

**Comment by pfefferle** [comment]
Either this or as issue in the post-kinds repo

**Comment by pfefferle** [comment]
I will close this, because it is no Webmention bug and will try to remove the auto generator of the WordPress headlines
