### ISSUE TITLE
Most webmentions are not displayed anymore

### ISSUE THREAD

**Issue by epischel** [pfefferle/wordpress-webmention#190]
Probably not a bug of this plugin but I post it anyway.

webmentions (via brid.gy) do not seem to be displayed anymore in most themes. Only classic/default theme show them. Example: [this blogpost.](https://www.epischel.de/wordpress/2018/06/playlist-of-robert-smiths-show-on-bbc6/)   It has 14 webmentions but shows only one (the only actual response on twitter, the rests are retweets and likes). It seems a problem with wp_list_comments. Classic theme uses foreach ($comments as $comment) and shows all webmentions. I'm using sempress theme.

I hope someone can help. Thanks.

**Comment by armingrewe** [comment]
Not sure what you mean with classic/default theme?
I run 3 different themes (2013, 2015 and 2016 I think, would need to check) and as far as I can tell the webmentions show just fine.

**Comment by pfefferle** [comment]
Can you try to enable comments and/or to disable facepiles?

**Comment by epischel** [comment]
I enabled comments. Now it shows likes and reposts. Facepiles are on.

**Comment by pfefferle** [comment]
Ok, the facepile feature uses an action of the comment form, that seems to not be triggered if comments are disabled. I will have a look if there is a better hook, we can use. Thanks for your report!

**Comment by epischel** [comment]
Gerne. (I disabled comments after 60 days or so b/c of comment spam.)

**Comment by pfefferle** [comment]
@epischel can you re-test with the newest version of the semantic-linkbacks plugin?

**Comment by epischel** [comment]
Works now. I'm not sure why there are now actual faces but names instead (could use some spaces inbetween btw), I don't know if I actually want this feature because of GDPR.
Thanks for fixing the issue.

**Comment by pfefferle** [comment]
this is a problem of missing images... that happens if a twitter user changes his avatar for example... we are working on a solution, but with GDPR it is not that easy to cache images...

**Comment by pfefferle** [comment]
will close this for now... please re-open if there is still something to fix...
