### ISSUE TITLE
Webmention facepiles do not display when Jetpack feature "Let readers use WordPress.com, Twitter, Facebook, or Google+ accounts to comment” is enabled.

### ISSUE THREAD

**Issue by khurtwilliams** [pfefferle/wordpress-webmention#194]
Webmention facepiles do not display when WordPress feature "**Let readers use WordPress.com, Twitter, Facebook, or Google+ accounts to comment**” is enabled.

To duplicate, enable " "Let readers use WordPress.com, Twitter, Facebook, or Google+ accounts to comment” in Jetpack.

Visit webpage with Webmention facepiles.

Jetpack setting:

![Screen Shot 2019-04-17 at 4 48 56 PM](https://user-images.githubusercontent.com/686971/56320249-b6d1b800-6131-11e9-822e-85b0f47ada1d.jpg)

Behaviour seen:

![Screen Shot 2019-04-17 at 4 49 23 PM](https://user-images.githubusercontent.com/686971/56320263-c18c4d00-6131-11e9-91ed-13935d316a3d.jpg)

When "Let readers use WordPress.com, Twitter, Facebook, or Google+ accounts to comment” is disabled in Jetpack. 

![Screen Shot 2019-04-17 at 4 48 02 PM](https://user-images.githubusercontent.com/686971/56320315-e254a280-6131-11e9-9e5a-f56350883873.jpg)

Webmention facepiles are displayed as expected.

![Screen Shot 2019-04-17 at 4 48 39 PM](https://user-images.githubusercontent.com/686971/56320342-f4364580-6131-11e9-9c16-bf25f350fafd.jpg)

**Comment by dshanske** [comment]
@khurtwilliams Facepiles are in Semantic Linkbacks, not Webmentions. However, working on an eventual merge. But until then, suggest this move over to the other repo.

**Comment by khurtwilliams** [comment]
Agreed. Not sure how to do that so I may recreate over there.
