### ISSUE TITLE
Including Dependencies

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-webmention#197]
Had proposed that instead of storing composer provided dependencies in the vendor directory, it be copied to another directory as it is not being included using composer.

Suggest to indicate it is a library, perhaps /lib ?

**Comment by dshanske** [comment]
Well, we've never added autoload to a plugin, I'm fine with starting to...

**Comment by dshanske** [comment]
This works. If we are using autoload, then I would want it in the vendor directory

**Comment by dshanske** [comment]
The only thing I have to ask is how this will address version conflict, as other plugins include php-mf2. Admittedly, they are mostly something I can influence.

**Comment by dshanske** [comment]
Looking at the coding and reading up a bit on the topic, it looks like we'd need to bundle an autoloader for when people don't have composer installed. Neither example shows a bundled vendor directory, so still concerned about mixing the dev and bundled dependencies. But let me see if I can redo the plugin to work with autoloading as the next step then.

**Comment by pfefferle** [comment]
Hmm, but you are right, we get problems with autoloading because of the mf2 library.

**Comment by dshanske** [comment]
I am thinking of using an autoloader though, but might need to based on the scaffold one. Also, might be time to namespace. Let me experiment.

**Comment by pfefferle** [comment]
perhaps not the best plugin to start that experiment...

**Comment by dshanske** [comment]
Then I will try a version of my original plan that separates out the dependencies but doesn't use composer to load them.

**Comment by dshanske** [comment]
@pfefferle Did another commit to that branch. This version automatically loads everything in the includes directory that ends in .php. It moves the init functions inside the class files that load them. It moves the Parser into a lib directory that has the license and README file.

**Comment by dshanske** [comment]
@pfefferle I have built a simple PHP 5.3 compatible autoload function into Parse This and I am going to refactor so it could be used without the feed parsing portion. I already made the SimplePie requirement optional. I might take another stab at this.

**Comment by dshanske** [comment]
Resolved via https://github.com/pfefferle/wordpress-webmention/commit/964eedeabcf7d7e997cf85084284f01f3ab0f6a1
