### ISSUE TITLE
Removal of Webmention_Plugin Class Broke Many Things

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-webmention#200]
A lot of things I wrote happen to check for the existence of the Webmention_Plugin class. Why did you remove it? Going to switch to the 'send_webmention' function for same. But there seems to be no reason why you changed to remove the class.

**Comment by pfefferle** [comment]
Because of the WordPress coding standard. But I made the changes a while ago and sadly forgot that I did so... I will re-add the class in a `deprecated.php` file.

**Comment by dshanske** [comment]
Not needed. I instituted a change

**Comment by pfefferle** [comment]
sorry!
