### ISSUE TITLE
GIFs do not display in webmention backfed from Twitter via Brid.gy.

### ISSUE THREAD

**Issue by kimberlyhirsh** [pfefferle/wordpress-webmention#201]
See comment at [kimberlyhirsh.com/2019/07/29/8561/#comments](https://kimberlyhirsh.com/2019/07/29/8561/#comments) backfed from [twitter.com/thoughtsofaphd/status/1155842810110783488](https://twitter.com/thoughtsofaphd/status/1155842810110783488).

**Comment by pfefferle** [comment]
Are you using the Semantic Linkback plugin?

**Comment by kimberlyhirsh** [comment]
Yes. Happy to file there instead if I should.

**Comment by pfefferle** [comment]
No problem 😊

It seems that SL is not detecting the reply as a reply.

**Comment by snarfed** [comment]
thanks for investigating! i'm seeing this too. example: https://snarfed.org/2019-08-05_38215#comment-2738608 , source URL is https://brid-gy.appspot.com/comment/twitter/schnarfed/1158577582020763648/1158577870391906304 .

mf2 seems ok to me. only notable feature is that it's missing `content`.

```json
{
    "type": ["h-entry"],
    "properties": {
        "name": [""],
        "url": ["https://twitter.com/szarka/status/1158577870391906304"],
        "video": ["https://video.twimg.com/tweet_video/EBQYbU-XoAAAaaf.mp4"],
        "in-reply-to": [
            "https://twitter.com/schnarfed/status/1158577582020763648",
            "https://snarfed.org/2019-08-05_38215"
        ],
        "published": ["2019-08-06T03:17:44+00:00"],
        "..."
    }
}
```

**Comment by pfefferle** [comment]
Why not adding the video code as `e-content`? At least in the FAQ it is listed as required for `h-entry` http://microformats.org/wiki/h-entry#what_is_the_bare_minimum_list_of_required_properties_on_an_h-entry

**Comment by snarfed** [comment]
sure, i could consider that. is that definitely the root cause of the problem here, and adding `e-content` would fix definitely it?

technically that microformats.org FAQ says content is a "should" for a "typical" `h-entry`, not a strict requirement:

> Beyond the bare minimum, a typical h-entry should have the following as well
