### ISSUE TITLE
Support webmention to media urls

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-webmention#203]
Can attach them to the attachment page.

**Comment by tw2113** [comment]
Could potentially output the webmention details on the attachment UI and whatnot.

One thing to keep in mind for anyone stopping by is that attachments are post types and have many matching features as other post types, but they also get special treatment in WP as well.

**Comment by dshanske** [comment]
I've already written the preliminary code for this. Should have received in, then can test presentation if any.

**Comment by pfefferle** [comment]
@dahanske can you split of the code to a simple merge request?

**Comment by dshanske** [comment]
I'd planned on it. As I'm abandoning the test branch.

**Comment by dshanske** [comment]
Addressed in #221
