### ISSUE TITLE
Add X-Forwarded-For Header to Webmention Verification

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-webmention#204]
WordPress does a header for verifying pingbacks.

https://indieweb.org/Webmention-brainstorming#using_x-forwarded-for_to_mitigate_DDoS_abuse

There is a proposal to add a similar header to the webmention requests.

**Comment by Lewiscowles1986** [comment]
CloudFoundry and many Web application firewalls will rightly strip this header. It could affect who can use.

I think it would get overwritten (clobbered) for anyone in a cloud hosting environment.

**Comment by dshanske** [comment]
@Lewiscowles1986 Why rightly?

**Comment by Lewiscowles1986** [comment]
It's a proxying header. If it were trusted you could masquerade, bypass external client request protections

**Comment by dshanske** [comment]
Trusted is different than blocking.

**Comment by Lewiscowles1986** [comment]
I'm not getting into a debate over this. I've told you you can listen or not. Check or not, but I've done the right thing letting you know my experience with this header.

**Comment by dshanske** [comment]
@Lewiscowles1986 Wasn't trying to offend. Apologies.

**Comment by Lewiscowles1986** [comment]
Oh I didn't take it as offence. Apologies if it sounded like I was or I've offended you. 

I was trying to draw a line under notifications as I don't have a lot more to add. 

For clarity `CURL -v {endpoint}` request to a script in a cloudfoundry (perhaps any proxied / load balanced environment) will show the value not as sent in.

This is multi-faceted (the why). It's not security alone
