### ISSUE TITLE
No new webmentions since upgrading to 3.8.10

### ISSUE THREAD

**Issue by armingrewe** [pfefferle/wordpress-webmention#206]
Not sure how to investigate this, but since upgrading to 3.8.10 no new webmention has come through. Bridgy is sending them (see https://brid.gy/twitter/islayblog), but nothing seems to come through at my end.
The last one I can see is from Friday early evening (before the upgrade), none of the six (as of writing this) since then is showing up.

Anyone else having problems? What I can I look at to investigate this?

**Comment by dshanske** [comment]
Did you try one manually?

**Comment by dshanske** [comment]
Found the problem. A misplaced parentheses. Sending PR

**Comment by armingrewe** [comment]
When I try that it comes back with this:
`<br />
<b>Warning</b>:  call_user_func_array() expects parameter 1 to be a valid callback, array must have exactly two members in <b>/homepages/24/d16081732/htdocs/newislayorguk/wp-includes/class-wp-hook.php</b> on line <b>286</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /homepages/24/d16081732/htdocs/newislayorguk/wp-includes/class-wp-hook.php:286) in <b>/homepages/24/d16081732/htdocs/newislayorguk/wp-includes/rest-api/class-wp-rest-server.php</b> on line <b>1258</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /homepages/24/d16081732/htdocs/newislayorguk/wp-includes/class-wp-hook.php:286) in <b>/homepages/24/d16081732/htdocs/newislayorguk/wp-includes/rest-api.php</b> on line <b>587</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /homepages/24/d16081732/htdocs/newislayorguk/wp-includes/class-wp-hook.php:286) in <b>/homepages/24/d16081732/htdocs/newislayorguk/wp-includes/rest-api.php</b> on line <b>588</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /homepages/24/d16081732/htdocs/newislayorguk/wp-includes/class-wp-hook.php:286) in <b>/homepages/24/d16081732/htdocs/newislayorguk/wp-includes/rest-api.php</b> on line <b>589</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /homepages/24/d16081732/htdocs/newislayorguk/wp-includes/class-wp-hook.php:286) in <b>/homepages/24/d16081732/htdocs/newislayorguk/wp-includes/rest-api.php</b> on line <b>590</b><br />
`
followed by some HTML (which I believe to be the confirmation page)

**Comment by dshanske** [comment]
@armingrewe There's a PR awaiting @pfefferle to review. This is me. I misplaced a ).

**Comment by armingrewe** [comment]
@dshanske our posts must have crossed, didn't see yours when I sent mine. Thanks for fixing so quickly!

**Comment by armingrewe** [comment]
Thanks for fixing, just installed the update and resent the Twitter likes from Bridgy and all came through fine.

**Comment by dshanske** [comment]
@armingrewe And now auto approve by domain should be working again
