### ISSUE TITLE
Link HTTP header missing from WebMention plugin

### ISSUE THREAD

**Issue by Lewiscowles1986** [pfefferle/wordpress-webmention#211]
I was trying to understand the technical implementation of the w3c guide.

So I upgraded my WP test environment and installed the plugin. It's fantastic. Thank you for spending time on this.

view-source:https://wp.dh.codesign2.co.uk/2019/08/test-blog/?v=79cba1185463

I can see that the header method should be called. 

https://github.com/pfefferle/wordpress-webmention/blob/master/includes/class-webmention-receiver.php#L836-L843

https://github.com/pfefferle/wordpress-webmention/blob/master/includes/class-webmention-receiver.php#L23

It's not short-circuited like the WordPress native so I can't think of anything other than PHP runtime configuration stopping this.

https://github.com/WordPress/WordPress/blob/master/wp-includes/link-template.php#L3852-L3871

oh WP calls this method in only one place

https://github.com/WordPress/WordPress/blob/master/wp-includes/default-filters.php#L301

One problem I do see is that the value would clobber other plugin values.

Link headers support multiple values. It would be nice to get the current header value and then clobber the concatenation of values at the time of setting value. (most likely PHP config dependent).

**Comment by Lewiscowles1986** [comment]
I think I got this. Open to a PR?

**Comment by pfefferle** [comment]
sure, but I can see no problems on my installation... The `header` function uses `$replace = false`...

**Comment by pfefferle** [comment]
I also can't see problems on your site...

**Comment by Lewiscowles1986** [comment]
I had a bit of a go at this. I'm testing it now https://github.com/pfefferle/wordpress-webmention/pull/212/

**Comment by Lewiscowles1986** [comment]
Looks like a caching issue. Unsure how as multiple clients were showing, but sure enough, after the PR, someone pointed out they saw all headers, I checked. There they were
