### ISSUE TITLE
Semantic Linkback Data picked up wrong Canonical Url

### ISSUE THREAD

**Issue by bekoli** [pfefferle/wordpress-webmention#216]
I got a webmention (v3.8.11) on an blog article from _my own_ blog (which is fine) but the Semantic Linback Data's Canonical url is off and I don't know why.

![image](https://user-images.githubusercontent.com/5016428/63650083-f2673900-c746-11e9-9e61-2624a36d38bf.png)

I got the Github URL in my page source here as part of a Social Media Rel Me List by the Independent Publisher theme and not as e.g. Site Address setting:

```html
<a class="icon-github url u-url" href="https://github.com/bekoli" title="Beko Pharm @ GitHub"><span class="relmename">github</span>
```

Tbf I don't know exactly how this _should_ work so it may be my own fault.

What do I have do change that the Webmention doesn't show as "Beko Pharm mentioned this Article on github.com." since this is clearly wrong.

**Comment by dshanske** [comment]
Yes, but it is how it is being parsed, which is a theme issue, as opposed to an issue with Semantic Linkbacks. It sees those links as inside instead of outside the post.

**Comment by dshanske** [comment]
Can try to help with that

**Comment by bekoli** [comment]
Thanks for your reply @dshanske. I've no link to Github within the `<article>` scope but it can be read when traversing the DOM upwards. Is this what the problem is?

What is the plugin exactly looking for? I fail to identify a fitting property at e.g. https://schema.org/BlogPosting

**Comment by dshanske** [comment]
The Semantic Linkbacks plugin currently handles this, not webmention. But it uses microformats 2, you can look at the parser it uses at php.microformats.io.

**Comment by bekoli** [comment]
Found it: https://github.com/pfefferle/wordpress-semantic-linkbacks/blob/26e197146a2c80327ffa8651fab7f87ad7fc8efc/includes/class-linkbacks-mf2-handler.php#L252

And yes it is indeed the first url parsed:

![image](https://user-images.githubusercontent.com/5016428/63651656-7de8c600-c757-11e9-9d77-df7b8eceeb28.png)

I'm not sure that this behaivor makes sense. Should I report it over at https://github.com/pfefferle/wordpress-semantic-linkbacks or just make sure that the mf2 parser lists the blog url first?

**Comment by pfefferle** [comment]
I think it is, as @dshanske said, a theme problem, not a problem of the Webmention/SL plugin. Do you use SemPress or Autonomie/ZenPress?

**Comment by pfefferle** [comment]
And there is another theme problem, the „real“ permalink is not listed anywhere...

**Comment by dshanske** [comment]
I have a fork of Independent Publisher called Indieweb Publisher that might satisfy

**Comment by bekoli** [comment]
I found out that there is Independent Publisher 2 by now and when I parse this I get also a canonical url:

![image](https://user-images.githubusercontent.com/5016428/63651930-7119a180-c75a-11e9-9054-c6c17f7089c6.png)

alas I don't see this parsed in wordpress-semantic-linkbacks, no?

**Comment by pfefferle** [comment]
Canonical is not used by SL because it is a global information that relates to the page and not necessarily to the article (h-entry).

**Comment by dshanske** [comment]
I checked my other implementation of the parsing code and it still interprets it similarly because of the issues identified. There are some mitigations I can think of, such as if there are multiple u-urls preferring the one on the same domain, but that wouldn't have helped here.

**Comment by bekoli** [comment]
I start go get the idea. Thanks for your input. I'll edit this to get the canonical url first as hotfix and migrate to a theme that doesn't have this issue at all later.
