### ISSUE TITLE
Increase semantic validation of endpoint url output.

### ISSUE THREAD

**Issue by tw2113** [pfefferle/wordpress-webmention#219]
We have some details covered like doctypes and charsets, but some details are hardcoded or simply disregarded. Let's harden this up.

**Comment by tw2113** [comment]
I believe this is regarding files like https://github.com/pfefferle/wordpress-webmention/blob/master/templates/webmention-endpoint-form.php

**Comment by dshanske** [comment]
No objection.

**Comment by dshanske** [comment]
The templates were, in my opinion, designed to make customizing the HTML display pieces easier and clearer and not have HTML generated in the middle of a large function file

**Comment by tw2113** [comment]
I think we're good in this state and am going to close the issue. We can return in the future if needed.
