### ISSUE TITLE
Developer Documentation

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-webmention#229]
Document all filters and global functions and reference some developer options in the readme.

**Comment by tw2113** [comment]
@dshanske are you thinking some type of generated documentation as well for this? Similar to what's in the attachment?
![Screen Shot 2019-10-04 at 10 48 23 AM](https://user-images.githubusercontent.com/484075/66221435-93c1a300-e694-11e9-87af-66cba4513350.png)

Or more just in-code documentation and getting that as complete as can be?

**Comment by dshanske** [comment]
I was just thinking PHPDocs and in the readme, but more is good too

**Comment by tw2113** [comment]
I have work going on this over at https://github.com/tw2113/wordpress-webmention/tree/229-dev-docs
