### ISSUE TITLE
simple caching of web mention-endpoints

### ISSUE THREAD

**Issue by pfefferle** [pfefferle/wordpress-webmention#24]
thinking about http://codex.wordpress.org/Function_Reference/set_transient for a simple caching of the web mention endpoints

**Comment by dshanske** [comment]
How long would you cache?

**Comment by voxpelli** [comment]
I would skip this unless you actually are likely to post to the same URL many times within the span of a couple of minutes as I think even a multiple hour long cache is probably to long.

Also probably better to wait until it has proven to be an issue (not sure if it has yet) as caching surely adds some complexity to things and can cause unexpected behaviors and make debugging hard.

Maybe if some blogs needs it that you make it an opt-in? Either through the admin interface or through a filter/hook that can replace the normal fetching with a cache based one?

**Comment by dshanske** [comment]
I like the idea of making this an. expansion option.

**Comment by dshanske** [comment]
https://github.com/snarfed/bridgy/issues/701 - Have a look at this.
