### ISSUE TITLE
Mastodon webmention not working?

### ISSUE THREAD

**Issue by edent** [pfefferle/wordpress-webmention#246]
Brid.gy is sending me Webmentions from Twitter and Mastodon. The Twitter ones appear in my moderation queue, but the ones from Mastodon don't appear. I've checked the spam, bin, and approved queue and they're not in there.

The Bridgy log shows:
```
I 2019-12-25 08:51:10.701576 Sent! 
{
	'request': 'POST https://shkspr.mobi/blog/wp-json/webmention/1.0/endpoint (with source=https://brid-gy.appspot.com/comment/mastodon/@Edent@mastodon.social/103096701414898694/103096795282020265, target=https://shkspr.mobi/blog/2019/11/how-to-present-at-a-hack-day/)',
	'http_status': 200,
	'body': '{
		"link": "https:\\/\\/shkspr.mobi\\/blog\\/2019\\/11\\/how-to-present-at-a-hack-day\\/#comment-135587",
		"source": "https:\\/\\/brid-gy.appspot.com\\/comment\\/mastodon\\/@Edent@mastodon.social\\/103096701414898694\\/103096795282020265",
		"target": "https:\\/\\/shkspr.mobi\\/blog\\/2019\\/11\\/how-to-present-at-a-hack-day\\/",
		"code": "...",
		"message": "Webmention was successful"
	}'
}
```
I've manually sent the Webmention using the form on my blog. Again, it says it is successful, but nothing appears.

WordPress 5.3.2, IndieWeb Version 3.4.2, Webmention Version 4.0.1.

Is there any way to see the plugin's logs? Or to find out what's going awry?

**Comment by dshanske** [comment]
There is a hook set up for logging, however no actual logging is built into the plugin at this time.

**Comment by edent** [comment]
This is now working.
