### ISSUE TITLE
Change "approve & whitelist" to be inclusive and more reader friendly

### ISSUE THREAD

**Issue by jeremyfelt** [pfefferle/wordpress-webmention#252]
Howdy. Thanks for the excellent plugin! I've **really** been enjoying playing around with Webmentions finally.

I'd like to propose changing the "Approve & Whitelist" text below each pending comment to something [more inclusive](https://medium.com/@bronAtNuna/language-matters-7fced5d78f8d) and reader friendly.

"Approve and Allowlist" doesn't really read right, but "Approve and always allow" or "always allow" seem like decent alternatives. In addition to being inclusive, I think that an average blog owner would be more confident knowing what "always allow" means rather than "whitelist".

It appears that the language can change throughout as the option stored in the database is `webmention_approve_domains`, which does not cause any back-compat issues. It may be that the function, `transition_to_whitelist` needs to remain as is in case anyone had been removing that filter through another plugin.

I'm happy to submit a PR with changes if this fits. :)

**Comment by dshanske** [comment]
No objection. I thought of doing this when the feature was working better, as it seems to be malfunctioning at the moment.
