### ISSUE TITLE
Store Avatar images in Media Library

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-webmention#259]
I was reading the code that WordPress uses to store album art.

Album art is stored in the media library as a separate file when you upload the audio file. A hash is stored in meta that can be queried to avoid uploading the same file over and over again.

It means we preserve the avatar as it existed at the time. The avatar property already can be an attachment id.

I think this would make a good simple way to finally solve this problem

**Comment by pfefferle** [comment]
But can you store images in the Media Library without adding a User, that "owns"/"uploaded" the image? And are these images displayed in the Media Library or can you hide them? As a user, I do not want to have avatars in my Media Library? Or do you only want to "borrow" the logic?

**Comment by dshanske** [comment]
Yes, you can. They would be displayed in theory, but I can experiment with that

**Comment by dshanske** [comment]
The only other solution I can think of is running a full image store for avatar photos and that is much more complicated

**Comment by dshanske** [comment]
Closing favor of an avatar cache
