### ISSUE TITLE
Likes and reposts etc not displaying?

### ISSUE THREAD

**Issue by kevquirk** [pfefferle/wordpress-webmention#261]
Hi,

I've recently implemented Webmention into my site. When someone sends a webmention with a comment, it's fine and all is well with the world. However, is I receive a webmention that is a like, repost, bookmark etc. They don't display. Neither does the webmention form.

I have comments disabled right across my site, as I don't want to deal with WordPress comment spam. I see on issue #190 someone has a similar issue that appears to be resolved, however, that doesn't appear to be the case for me.

For example, [this post](https://kevq.uk/implementing-the-indieweb-into-my-website/) has a couple of resposts within the WP comments section, but it only shows the Webmentions with content.

Thanks.

**Comment by ndegruchy** [comment]
Kev,

I don't think you ever got your question answered before you used Webmention.io...

Regardless: You need comments enabled if you want to display and receive webmentions with this plugin. This was confusing to me, too. Perhaps a notification if you have comments disabled or something?

Thanks!
