### ISSUE TITLE
Empty title/content webmentions

### ISSUE THREAD

**Issue by ndegruchy** [pfefferle/wordpress-webmention#277]
I keep getting webmentions of various kinds that don't have a title (for things like "likes" or "bookmarks"). These properly show up in the comments system and on the page, but only the user's h-card image appears. The actual anchor element is created, but because there is no title, I presume it fills it with empty text.

Would it be possible to check for an empty string and just pre-fill it with some default-ish text like `"Visit {Kind}"` or similar?

**Comment by ndegruchy** [comment]
Here is an example:

## Comment Page
![Screenshot_2020-07-25 New Header Images Yes, I Like My Cats](https://user-images.githubusercontent.com/52262673/88461100-d85e3b00-ce6e-11ea-852d-c8f2fd957e7b.png)

## DOM that Makes Up the Comment Area
![Screenshot_20200725_120309](https://user-images.githubusercontent.com/52262673/88461106-e0b67600-ce6e-11ea-9d72-ac1b975c0bd8.png)

This is all using the Autonomie theme and the various IndieWeb plugins without any addiitonal CSS.

**Comment by pfefferle** [comment]
This seems to be the expected behavior. If you use facepiles, there will be only the Image. To also have some text, you have to disable the facepile feature for likes.

**Comment by ndegruchy** [comment]
> To also have some text, you have to disable the facepile feature for likes.

Hmm. Okay. I know I can do this with some CSS, like:

```css
.linkback-like-single > .u-url {
    content: "❤️ View Like";
    // Various padding and other alignment properties here
}
```

It'd be nice to see a configurable (even if through a filter) option for this. Thanks anyway.

**Comment by pfefferle** [comment]
@ndegruchy if you disable facepiles for this comment-type, you will see some more content:

> John Doe liked this Link on twitter.com.

Facepiles are by definition only a list of avatars: https://indieweb.org/facepile

**Comment by pfefferle** [comment]
If you want to filter the content, you can use https://github.com/pfefferle/wordpress-semantic-linkbacks/blob/master/includes/class-linkbacks-handler.php#L595 for the non-facepile customization. For the facepiles there is indeed nothing yet.

We are currently working on integration the Semantic Linkbacks plugin into the Webmention plugin and we will support filtering the content for that.
