### ISSUE TITLE
Blank or Broken webmentions

### ISSUE THREAD

**Issue by edent** [pfefferle/wordpress-webmention#289]
This page is set up to receive WebMentions – https://shkspr.mobi/blog/2020/09/a-floppy-disk-mp3-player-using-a-raspberry-pi/

**Works** sending a manual Webmention from https://hackaday.com/2020/09/07/the-floppy-disk-as-a-portable-music-format/ appeared correctly in my dashboard.

**Broken** sending a manual Webmention from https://www.hackster.io/news/terence-eden-s-techno-walkman-uses-a-raspberry-pi-the-opus-codec-and-floppy-disks-for-lo-fi-beats-9ee593685f75 shows “Webmention was successful” but in my Dashboard I see a blank comment from “Anonymous”. If I go to edit the comment, it is completely blank. I can see my IP address, but that’s it.

**Not detected** sending a manual Webmention from https://www.tomshardware.com/news/retro-raspberry-pi-floppy-disk-walkman gives the error “Source URL not found”. I can see the correct URL in the body of that page.

I experience broken Webmentions fairly regularly. I get completely blank “anonymous” comments.

Is there any way to debug what’s actually happening?

**Comment by pfefferle** [comment]
hmmm, the main problem is, that all broken sites do not have any kind of semantics, so that might be the reason behind it, but it should not be broken, but at least show some kind of default text.

**Comment by edent** [comment]
Here's one I just found.

https://www.metafilter.com/188664/GLaDOS-v11

When I past that into the Webmention form on the blogpost, this is what appears in my moderation queue.
![Screenshot_2020-09-16 Comments (1) ‹ Terence Eden’s Blog — WordPress](https://user-images.githubusercontent.com/837136/93316014-982e8f80-f803-11ea-84e9-9154199f3cdb.png)
How can I debug this to see where the data is being lost?

**Comment by edent** [comment]
Just tested on 4.0.4, still getting this. Is there a debug function so I can see where the issue is?

**Comment by edent** [comment]
I've added some debug output in https://github.com/pfefferle/wordpress-webmention/blob/b212cf16698b79a61856cb5f736604059fc5a0ac/includes/class-webmention-receiver.php#L402

This is what is being returned:

```
array(5) { 
   ["link"]=> string(16) "/#comment-178863"
   ["source"]=> string(72) "https://www.vice.com/en/article/dy8z5z/very-slow-website-speed-slowww-ml"
   ["target"]=> string(75) "https://shkspr.mobi/blog/2020/10/introducing-slowww-ml-the-slow-web-server/"
   ["code"]=> string(7) "success"
   ["message"]=> string(25) "Webmention was successful" 
} 
```

The full `$comment` is:

```
array(19) {
  ["content_type"]=>  string(24) "text/html; charset=utf-8"
  ["remote_source_original"]=>  string(148051) "<!DOCTYPE html>......"
  ["comment_type"]=>  string(10) "webmention"
  ["comment_agent"]=>  string(76) "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0"
  ["comment_date"]=>  string(19) "2020-10-27 12:49:53"
  ["comment_date_gmt"]=>  string(19) "2020-10-27 12:49:53"
  ["comment_meta"]=>  array(4) {
    ["webmention_created_at"]=>    string(19) "2020-10-27 12:49:53"
    ["protocol"]=>    string(10) "webmention"
    ["webmention_source_url"]=>    string(72) "https://www.vice.com/en/article/dy8z5z/very-slow-website-speed-slowww-ml"
    ["webmention_target_url"]=>    string(75) "https://shkspr.mobi/blog/2020/10/introducing-slowww-ml-the-slow-web-server/"
  }
  ["source"]=>  string(72) "https://www.vice.com/en/article/dy8z5z/very-slow-website-speed-slowww-ml"
  ["target"]=>  string(75) "https://shkspr.mobi/blog/2020/10/introducing-slowww-ml-the-slow-web-server/"
  ["vouch"]=>  NULL
  ["comment_post_ID"]=>  int(37039)
  ["comment_author_IP"]=>  string(11) "123.444.555.666" (redacted for my privacy)
  ["comment_author_url"]=>  string(72) "https://www.vice.com/en/article/dy8z5z/very-slow-website-speed-slowww-ml"
  ["comment_parent"]=>  string(0) ""
  ["comment_author_email"]=>  string(0) ""
  ["comment_author"]=>  string(56) "Maybe the Internet Would Suck Less If It Was Really Slow"
  ["comment_content"]=>  string(125) "This Article was mentioned on <a href="https://www.vice.com/en/article/dy8z5z/very-slow-website-speed-slowww-ml">vice.com</a>"
  ["comment_ID"]=>  int(178868)
```

Nothing seems obviously wrong. But the resultant comment is still blank!

**Comment by edent** [comment]
Aha! It needs to run `unset($commentdata["remote_source_original"]);` before submitting the comment.
PR incoming once I've tested it a bit more.

**Comment by edent** [comment]
Hmmm, nope, that doesn't work because the semantic-linkbacks enhancer doesn't run if there's no `remote_source_original`.
