### ISSUE TITLE
Label should refer to a unique ID

### ISSUE THREAD

**Issue by janboddez** [pfefferle/wordpress-webmention#309]
https://github.com/pfefferle/wordpress-webmention/blob/b212cf16698b79a61856cb5f736604059fc5a0ac/templates/webmention-settings.php#L65-L66

Clicking on a label does not (un)check the box next to it, because it references the `value` attribute rather than a unique ID. Easiest solution would be to wrap the checkbox in the `label` tags (and ditch the `for` attribute as well as the [invalid] `id` attributes). Another would be to make the IDs unique and have the `for` attributes refer to them.

**Comment by pfefferle** [comment]
Is fixes in 5.X
