### ISSUE TITLE
Add option to set parent comment ID for webmention replys

### ISSUE THREAD

**Issue by florianbrinkmann** [pfefferle/wordpress-webmention#310]
When I share a post on Twitter and users are replying to the tweet, I get those tweets as comments in WordPress. But because there is no relation between those comments, they are all displayed as first-level comments, even if the replys are threaded, so I find myself opening PHPmyAdmin to manually set the comment parent IDs to get nice threaded comments (you can see an example here https://florianbrinkmann.com/wechsel-windows-auf-ubuntu-11634/#comments)

Would it be possible to add a field to webmention replys for editing the comment parent ID value (maybe hidden by a option), so that this could be directly managed in the WordPress admin?

**Comment by dshanske** [comment]
@florianbrinkmann Try https://wordpress.org/plugins/modify-comment-parent/ It seems to do what you want already.

For now, considering Twitter is out of Bridgy...which I assume is the source of the tweets, I wonder if there is a better way to thread these for future Bridged comments in future. Webmention comments should work if they are to specific comment URLs(with the argument for the specific comment)

Closing this for now in favor of looking for better ways to do this automatically for now.
