### ISSUE TITLE
Feature Request: save webmention icons locally

### ISSUE THREAD

**Issue by davidwolfpaw** [pfefferle/wordpress-webmention#311]
If a post has multiple likes, retweets, comments, etc, that means lots of images need to get fetched from Mastodon and Twitter.

Those links are all separate requests to third party services that can slow down page load. Additionally, those links could go bad, and leave a page with multiple image requests that 404.

I am suggesting that comment images be saved locally, to avoid both of those issues.

**Comment by dshanske** [comment]
@davidwolfpaw See recent PR on this.

**Comment by dshanske** [comment]
I actually want to rewrite the PR to be broader.

**Comment by dshanske** [comment]
Also, I may experiment with it as a separate plugin to see how it works in practice.

**Comment by pfefferle** [comment]
As @dshanske already said: there is an open pull request for that, that needs some more attention to add missing things like:

* scan past posts
* use hashes insted of usernames
* normalize URLs to not save avatars twice

I hope I or @dshanske will find some time, to finish the PR.

**Comment by pfefferle** [comment]
The problem is, that twitter does not have consistent avatar URLs. They invalidate if a twitter user changes his avatar.

**Comment by dshanske** [comment]
I intend to do some work on it and try to use the code to see what happens

**Comment by dshanske** [comment]
There has been a decision to not include avatar caching within the plugin at this time. The Avatar Privacy plugin currently caches webmention avatars for a customizable period of time, but not forever and is available immediately. And I'm going to take the code @pfefferle and I worked on for this and put it into a repo as an independent piece if someone wants to use it or if I want to work on it.
