### ISSUE TITLE
Bug: some images not loading from Twitter

### ISSUE THREAD

**Issue by davidwolfpaw** [pfefferle/wordpress-webmention#312]
Most posts on my site have likes, tweet comments, and retweets that have links to broken Twitter images. This does not look good on the page, and leads to lots of requests that 404.

This is an example post with the issue (screenshot attached): https://davidwolfpaw.com/getting-started-on-mastodon/

![Screen Shot 2021-04-13 at 9 02 27 AM](https://user-images.githubusercontent.com/1971070/114556729-fd7e1e00-9c36-11eb-812e-be8704faf593.jpg)

If I attempt to view one of those images in the browser, for instance https://pbs.twimg.com/profile_images/1223053903811555333/R-lsE2nH.jpg, I get the following error message:
The image “https://pbs.twimg.com/profile_images/1223053903811555333/R-lsE2nH.jpg” cannot be displayed because it contains errors.

**Comment by pfefferle** [comment]
There should be a quick fix in the latest version of the plugin. Does that work for you?

**Comment by dshanske** [comment]
Closed due fix being inline for some time.
