### ISSUE TITLE
Webmention sent from WordPress site included text from different post

### ISSUE THREAD

**Issue by TheDavidJohnson** [pfefferle/wordpress-webmention#33]
I just installed the plugin on my WordPress site today and sent a webmention by publishing [this post](http://www.epiphanydigest.com/2014/10/18/new-social-tool/).

The target of my webmention was [this post](http://stream.withknown.com/2014/webmention-an-introduction-for-developers) running [idno](https://github.com/idno/idno)

When the webmention was posted as a comment, the text came from a [previous post](http://www.epiphanydigest.com/2014/09/04/join-michael-bruce/) on EpiphanyDigest instead of the new one I published today. This, of course, made my comment look very spammy since it mentioned some injury attorneys (!).

Have I misunderstood the usage of the plugin, perhaps? I'm happy to provide any additional info as needed for diagnosis.

Thanks!

**Comment by pfefferle** [comment]
I will close this for now
