### ISSUE TITLE
Semantic linkbacks installation from Webmention settings doesn’t work

### ISSUE THREAD

**Issue by angelocali** [pfefferle/wordpress-webmention#330]
WordPress Version: 5.9.2
PHP-Version: 7.4.28

To reproduce this:
1. Under `Settings -> Webmention` is a warning that recommends installing and activating the `Semantic Linkbacks Plugin`.
2. Click `Semantic Linkbacks Plugin` within the warning text - A plugin details modal appears
3. Click `Install Now` within the modal - Nothing happens

The installation from `Plugins -> Add New` works flawlessly.

**Comment by dshanske** [comment]
Semantic Linkbacks is now deprecated.
