### ISSUE TITLE
Potential issue when sending vouch parameter

### ISSUE THREAD

**Issue by gRegorLove** [pfefferle/wordpress-webmention#333]
I posted [this reply](https://gregorlove.com/2022/05/hi-matt/) to a WordPress post and my automated Webmention-sending included a `vouch` parameter. I received an HTTP 400 error with body:

`{"code":"rest_missing_callback_param","message":"Missing parameter(s): source, target","data":{"status":400,"params":["source","target"]}}`

`target` and `source` parameters were included, so my initial thought was maybe the plugin failed to parse them due to an unexpected `vouch` param?

The webmention parameters my site sent:
```
source=https%3A%2F%2Fgregorlove.com%2F2022%2F05%2Fhi-matt%2F \
&target=https%3A%2F%2Flordmatt.co.uk%2Ftechnology%2Fthe-internet%2Fsocial-media%2Fjoining-the-indieweb \
&vouch=https%3A%2F%2Findieweb.org%2Fthis-week%2F2017-04-07.html
```

**Comment by gRegorLove** [comment]
@lordmatt, could you confirm what version of the WordPress Webmention plugin your site is running?

**Comment by pfefferle** [comment]
@gRegorLove is this error only when you send the vouch param?

**Comment by gRegorLove** [comment]
@pfefferle I haven't tried manually re-sending it via curl yet. I ended up using the form on the original post to submit my URL. I got a success message.

**Comment by gRegorLove** [comment]
I experienced this again with another WP site. This [like post](https://gregorlove.com/2022/11/star-asserting-the-right-to-exist/) and the sent webmention:

```
source=https%3A%2F%2Fgregorlove.com%2F2022%2F11%2Fstar-asserting-the-right-to-exist%2F
&target=https%3A%2F%2Ftracydurnell.com%2F2022%2F11%2F23%2Fasserting-the-right-to-exist-in-public-online-spaces
&vouch=https%3A%2F%2Findieweb.org%2Fthis-week%2F2017-04-07.html
```

Response:
```json
{"code":"rest_missing_callback_param","message":"Missing parameter(s): source, target","data":{"status":400,"params":["source","target"]}}
```

**Comment by pfefferle** [comment]
This seems to be fixed now, feel free to re-open if not.
