### ISSUE TITLE
Webmention on WordPress 6.0.1

### ISSUE THREAD

**Issue by mikesplaces** [pfefferle/wordpress-webmention#338]
Hello. I have a brand new website running self-hosted wordpress based on DigitalOcean's app install. I decided to test web mentions by creating an anonymous post on write.as and then go to my blog at https://mpmilestogo.site to the blog post at https://mpmilestogo.site/2022/07/13/creating-content-on-the-blog-and-substack/. When I enter the anonymous post URL which has a link to this post, I get a critical wordpress error but no other real information. I noticed this also on a friend's website when I created a post that linked to their blog and entered the post. For the installation, I just did the default install of webmention plugin and activated it in wordpress. The attachment is what happens afterwards.

<img width="815" alt="Screen Shot 2022-07-13 at 8 01 12 PM" src="https://user-images.githubusercontent.com/78836916/178862494-47e5cebc-4df7-40cd-b65c-5717323ff1c9.png">

**Comment by mikesplaces** [comment]
Hi. I went to the VPS and looked at the error logs for apache and I found an error like this for the semantic-linkbacks plugin:

WP->main()\n#19 /var/www/html/wp-blog-header.php(16): wp()\n#20 /var/www/html/index.php(17): require('...')\n#21 {main}\n  thrown in /var/www/html/wp-content/plugins/semantic-linkbacks/includes/class-linkbacks-mf2-handler.php on line 399, referer: https://mpmilestogo.site/2022/07/13/creating-content-on-the-blog-and-substack/

So I disabled that plugin and now webmentions work okay. I don't really know what that all means :-). Just thought you could check on the other plugin.

**Comment by dshanske** [comment]
The other plugin is being folded into Webmentions, but we're still fixing bugs until that happens.

**Comment by dshanske** [comment]
I have a guess that it involves strict typing as line 399 in that plugin is about counting.

**Comment by dshanske** [comment]
@mikesplaces Do you know what version of PHP the new instance is running? PHP8 started doing something I think might be related.

**Comment by dshanske** [comment]
https://github.com/pfefferle/wordpress-semantic-linkbacks/issues/258 Appears someone already identified the issue. Will write a fix.

**Comment by mikesplaces** [comment]
Yeah. I am looking at the DigitalOcean app info page and I grabbed a screenshot of what gets installed when I do the app install. It appears that PHP is at 7.4. I

<img width="526" alt="Screen Shot 2022-07-13 at 10 14 57 PM" src="https://user-images.githubusercontent.com/78836916/178890407-9b43d97e-0555-4961-8871-4f0deb965135.png">

**Comment by dshanske** [comment]
Semantic Linkbacks is now deprecated,.so we'll close this on that basis..If still happening with Webmention 5.0.0 please refile.
