### ISSUE TITLE
Webmentions on Custom Post Types

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-webmention#346]
I found a reason why Custom Post Types webmention sending wouldn't work.

Essentially, we trigger webmentions using do_pings, which is triggered by _publish_post_hook, which is triggered by publish_post.

Since that only applies to the 'post' post type, it means any pending webmentions won't be sent for any other post type until the next time someone publishes a 'post' post type.

We can fix this by creating our own trigger for publish_{post_type} that executes

	if ( ! wp_next_scheduled( 'do_pings' ) ) {
		wp_schedule_single_event( time(), 'do_pings' );
	}

It probably also explains a few more issues.

**Comment by pfefferle** [comment]
Oh, good point!

**Comment by tmichellemoore** [comment]
Thank you @dshanske for diagnosing this custom post type issue. I will not give up on them now!

(Originally published at: https://tmichellemoore.com/?p=151626)

**Comment by pfefferle** [comment]
@dshanske add your tweak for now and think about a different approach for the long term (to not slow down 5.X any more)?

**Comment by dshanske** [comment]
I think I'll do up a PR for both... I don't think it's a problem

**Comment by dshanske** [comment]
Resolved via #376
