### ISSUE TITLE
Vouch Support

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-webmention#35]
Implement Vouch Support. 

http://indiewebcamp.com/vouch

**Comment by pfefferle** [comment]
I don't think this should be part of the webmention plugin. Let me know if you need some actions/filter to build a third party plugin.

**Comment by voxpelli** [comment]
I'm a bit unsure about the traction of this IndieWeb concept as well – not that many people seems to have implemented it and I myself am not making it a top priority for [my endpoint](https://github.com/voxpelli/webpage-webmentions).

**Comment by pfefferle** [comment]
I will close this for now, because this should be implemented as an extra plugin. Feel free to request some actions/filters if you need them to implement it.

**Comment by dshanske** [comment]
In one of the commits I added in, the plugin merely passes the vouch parameter into the commentdata so it could be used in moderation. I think the strict interpretation of rejecting without a vouch parameter is premature and not yet worth considering.
