### ISSUE TITLE
php 8.1 fatal error on upgrade

### ISSUE THREAD

**Issue by shawfactor** [pfefferle/wordpress-webmention#352]
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Webmention\upgrader_overwrote_package(), 2 passed in /***/public_html/wp-includes/class-wp-hook.php on line 308 and exactly 3 expected in /home/melbour9/public_html/wp-content/plugins/webmention/webmention.php:155
Stack trace:
#0 /****/public_html/wp-includes/class-wp-hook.php(308): Webmention\upgrader_overwrote_package()
#1 /****/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#2 /****/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#3 /****/public_html/wp-admin/includes/class-plugin-upgrader.php(371): do_action()
#4 /****/public_html/wp-admin/update.php(51): Plugin_Upgrader->bulk_upgrade()
#5 /****/public_html/wp-admin/network/update.php(17): require('/home/melbour9/...')

**Comment by pfefferle** [comment]
hello @shawfactor :)

Thanks for reporting, but this is weird, the doku says there are three params. Can you give me a bit more details what exactly you did to receive the issue?
