### ISSUE TITLE
old wemention comment type creates fatal error

### ISSUE THREAD

**Issue by shawfactor** [pfefferle/wordpress-webmention#353]
Maybe some migration script did not run but I am getting a fatal error, I monkey patched it by doing this:

	public static function get_comment_type_attr( $type, $attr ) {
		$types  = self::get_comment_types();
		
		if (!empty($types[ $type ])){
		
            $return = $types[ $type ]->get( $attr );
            
		} else {
		    
		    $return = false;
		    
		}

		return apply_filters( "webmention_comment_type_{$attr}", $return, $type );
	}

see stack trace below.

stack trace is below
[07-Feb-2023 11:00:57 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /***/public_html/wp-content/plugins/webmention/includes/class-comment.php:48
Stack trace:
#0 /****/public_html/wp-content/plugins/webmention/includes/functions.php(66): Webmention\Comment::get_comment_type_attr('webmention', 'label')
#1 /****/public_html/wp-content/plugins/webmention/templates/webmention-comments.php(19): get_webmention_comment_type_attr('webmention', 'label')
#2 /****/public_html/wp-includes/comment-template.php(1550): require('/home/melbour9/...')
#3 /*****/public_html/wp-content/themes/lh-2015/content.php(65): comments_template()
#4 /****/public_html/wp-includes/template.php(785): require('/home/melbour9/...')
#5 /****/public_html/wp-includes/template.php(718): load_template('/home/melbour9/...', false, Array)
#6 /****/public_html/wp-includes/general-template.php(204): locate_template(Array, true, false, Array)
#7 /****/public_html/wp-content/themes/twentyfifteen/single.php(25): get_template_part('content', '')
#8 /****/public_html/wp-includes/template-loader.php(106): include('/home/melbour9/...')
#9 /****/public_html/wp-blog-header.php(19): require_once('/home/melbour9/...')
#10 /****/public_html/index.php(17): require('/home/melbour9/...')
#11 {main}
  thrown in /****/public_html/wp-content/plugins/webmention/includes/class-comment.php on line 48

**Comment by pfefferle** [comment]
Oh, which version have you used? The latest main-branch version?

**Comment by pfefferle** [comment]
It seems that there was really a hickup with the migration!

**Comment by pfefferle** [comment]
Can you recheck with the code I submitted?

**Comment by pfefferle** [comment]
@shawfactor is this one of a few or have you found some more of these comments? Can you check the comment-metas for this comment and add them to this issue? So maybe I can modify the migration script.

**Comment by shawfactor** [comment]
Yes obviously the migration script did not run,  (all webmentions created errors) but I have run it manually across all mys sites not

I am curious as to why you have closed the issue though?

The code could be improved by adding that check anyway.

**Comment by pfefferle** [comment]
I have added the check!

**Comment by pfefferle** [comment]
I modified it a bit, but in the end it is the same: https://github.com/pfefferle/wordpress-webmention/commit/f188ce5cf119f24253f3ec7c86846bb8113ae85d

**Comment by pfefferle** [comment]
@shawfactor how have you installed the latest version yet? Composer? (S)FTP? ZIP Upload? (I will try to figure out why the migration did not run).

Have you experienced any issues after running the migration manually?

**Comment by dshanske** [comment]
In another plugin, I triggered an update check on the settings page as a backup to the automatic
