### ISSUE TITLE
 Cross site scripting vulnerability

### ISSUE THREAD

**Issue by Michael-Brooks** [pfefferle/wordpress-webmention#357]
Hello,

I installed this plugin and was recently notified of a potential security flaw on my website. When a user went to [https://michaelbrooks.co.uk/restarting-my-podcast/?replytocom=</SCript><svG/onLoad=prompt(9)>](https://michaelbrooks.co.uk/restarting-my-podcast/?replytocom=%3c/SCript%3e%3csvG/onLoad=prompt(9)%3e) it would display a prompt where the user could inject JS.

![image](https://user-images.githubusercontent.com/3197231/223776788-945eef50-f39e-4aca-a95b-ec741527587a.png)

I spoke to WordPress.com helpdesk, who identified the issue was coming from this plugin. Here is the bounty that the hacker generated for my blog https://www.openbugbounty.org/reports/3211320/

**Comment by pfefferle** [comment]
hey @Michael-Brooks thanks for reporting, I saw the issue in the Webmention repo and am preparing a fix!

**Comment by pfefferle** [comment]
Fixed in 4.0.9! Thanks again for finding and reporting the issue!
