### ISSUE TITLE
Mentions aren't integrated into comments

### ISSUE THREAD

**Issue by edent** [pfefferle/wordpress-webmention#361]
Mentions which were previously displayed in my  comments, are now in a separate `<ul class="reaction-list">`

They also don't display the content - instead, they appear like a Facepile.

![mentions showing outside the comments.](https://user-images.githubusercontent.com/837136/230005000-3720a81c-9e53-46ef-a64e-3aa21cb0df5f.jpg)

This is a bit of a regression. I want mentions to appear as comments.

**Comment by edent** [comment]
This also breaks the number of comments displayed. My blog now shows the text "5 Comments" - but it displays as
* 1 repost
* 1 like
* 3 text comments

**Comment by edent** [comment]
The fix appears to be adding this to my theme's functions.php

```php
remove_action( 'init', array( '\Webmention\Comment_Walker', 'init' ) );
```

Might be worth adding that to the readme?

**Comment by armingrewe** [comment]
> In addition, links from Bridgy are now broken. For example, they link to https://brid.gy/post/twitter/edent/1643166753101430787 rather than the canonical URl.

I notice the same thing, so not sure if that's a theme issue or a different problem.

At least for Twitter from the looks of it academical, as it looks like the API is already d dead for brid.gy

**Comment by pfefferle** [comment]
But only global, there is no setting any more to enable/disable facepiles by type.

**Comment by edent** [comment]
Ah, I hadn't spotted that. Might be worth having it default to "off" for new installs?

**Comment by dshanske** [comment]
I would strongly disagree with off for new installs.

**Comment by dshanske** [comment]
We can restore the per reaction behavior if needed.

**Comment by lostfocus** [comment]
"off" for old installs would have been the best way, probably. But that ship has sailed.

**Comment by dshanske** [comment]
As this is an option, would close this. The per-reaction display type option should probably make a comeback, but will also explore the incoming rejection option I'd imagine at some point.

**Comment by lostfocus** [comment]
What about the broken brid.gy links?

**Comment by edent** [comment]
@lostfocus these seem to be working now. In any case, I replaced them with the canonical URl rather than going through brid.gy

**Comment by dshanske** [comment]
> What about the broken brid.gy links?

That's a separate issue.

**Comment by dshanske** [comment]
Bridgy cached them for now, but will be updating them

**Comment by lostfocus** [comment]
I haven't looked into the source code but before the update comments (or likes, reposts etc.) that came via bridgy linked to their original source. Now they link to bridgy. So it looks like it uses a different database field now. I guess (I hope!) the information is still somewhere in the database?

**Comment by pfefferle** [comment]
@lostfocus I messed up a migration step. I am working on a second migration to bring back the canonical URLs for version 5.1. sorry about that!
