### ISSUE TITLE
Undefined array key 1 in class-response.php on line 203

### ISSUE THREAD

**Issue by edent** [pfefferle/wordpress-webmention#369]
I'm seeing lots of error log entries with:

`PHP Warning:  Undefined array key 1 in /home/blog/wp-content/plugins/webmention/includes/class-response.php on line 203`

https://github.com/pfefferle/wordpress-webmention/blob/216b1b9727437a3c3d44d51476e4c551a14a9f6e/includes/class-response.php#L203

Appears to be part of `get_header_links()` - but I don't fully understand what the function does.

**Comment by pfefferle** [comment]
@edent do you maybe have an example URL that causes this error?

**Comment by edent** [comment]
@pfefferle I received a like which caused this.

Source: https://brid.gy/like/mastodon/@edent@mastodon.social/110213942689754872/41238
Target: https://shkspr.mobi/blog/2023/04/wget-is-much-faster-than-scp-or-rsync/

**Comment by pfefferle** [comment]
thanks, can you also tell me your PHP version?

**Comment by edent** [comment]
PHP 8.1.17
