### ISSUE TITLE
Make likes, repost and mention overlay emojis optional

### ISSUE THREAD

**Issue by danielcharrua** [pfefferle/wordpress-webmention#372]
Would be great to let users select to turn off/on overlay emojis on likes, repost, mentions, etc...

They are a good way to identify the mentions but do not add any value on design and I think they add "noise" (IMHO) to the mentions.

Thank you.

**Comment by dshanske** [comment]
In my original version, had planned to add options to have a row of images and a single icon at the beginning, the overlay option, etc. We're looking at templating, but some options that don't require code are probably warranted.

**Comment by dshanske** [comment]
Opted to go for this by filter instructions, rather than a setting.

**Comment by dshanske** [comment]
This technically makes this resolved.
