### ISSUE TITLE
Add comment type to edit comment screen

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-webmention#373]
The comment screen for editing does not show the comment type or other metadata by default. Create a better presentation here and explore bringing back converting one type into another.

**Comment by edent** [comment]
On my comment edit screen, I see this:

![Screenshot showing the metadata](https://user-images.githubusercontent.com/837136/231211025-fd66f7c6-e6a9-4d6f-835c-2730ce539592.png)

I can't edit it - but it does seem to show the metadata.

**Comment by dshanske** [comment]
I want to update that for the new era

**Comment by dshanske** [comment]
Resolved via #375
