### ISSUE TITLE
Add Support for Checking Client IP

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-webmention#38]
http://indiewebcamp.com/DDOS#Check_client_IP

Check the client IP of the incoming webmention POST request against the possible IPs of the source URL hostname — if they don’t match, mark the webmention for moderation."

**Comment by pfefferle** [comment]
Same as vouch support: https://github.com/pfefferle/wordpress-webmention/issues/35

**Comment by voxpelli** [comment]
An alternative would be to just forward the IP as suggested here: http://indiewebcamp.com/webmention#using_x-forwarded-for_to_mitigate_DDoS_abuse That way the source site itself can decide whether the IP is suspicious or not.

**Comment by pfefferle** [comment]
I will close this for now, because this should be implemented as an extra plugin. Feel free to request some actions/filters if you need them to implement it.
