### ISSUE TITLE
Add Expiring Token to Endpoint for DDOS Protection

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-webmention#39]
Add an expiring, random or encrypted token to webmention endpoints, preventing the accumulation of lists of endpoints and forcing attackers to look up the webmention endpoint of each of the sites they want to use to DDOS a victim.

http://indiewebcamp.com/DDOS#Expiring_token_in_endpoint

**Comment by pfefferle** [comment]
see: https://github.com/pfefferle/wordpress-webmention/pull/41
