### ISSUE TITLE
brid.gy fed produces wrong comment-types

### ISSUE THREAD

**Issue by pfefferle** [pfefferle/wordpress-webmention#391]
This "repost" is parsed as "mention": https://fed.brid.gy/render?id=https%3A%2F%2Findieweb.social%2Fusers%2Ftchambers%2Fstatuses%2F110216352333996097%2Factivity

**Comment by pfefferle** [comment]
@snarfed shouldn't the `u-repost-of` also use class `u-url` besides the `u-uid`???

We currently seem to only check `u-url`!

**Comment by pfefferle** [comment]
I hope I am not wrong, but shouldn't the parser work like that:

Search for a Mircoformat URL that has the link, check if the link has a reply-context, if not, go one element above and check there. So we seem to always find the `h-entry` element (that has no context) instead of the `h-cite`.

/cc @dshanske

**Comment by pfefferle** [comment]
@snarfed I added some tests for the new markup and our parser would work totally fine, if you would add `p-url` to every `p-uid`.

**Comment by snarfed** [comment]
Morning! I'm not on the computer yet, but I believe some BF posts like these omit u-url because there's no permalink for them on Mastodon.

Ideally they'd have one, but post type discovery and other webmention processing shouldn't strictly require u-url, right? https://indieweb.org/post-type-discovery#Algorithm

**Comment by snarfed** [comment]
u-uid on these posts points to the JSON AS2 activity, not a human-readable HTML page, which is why it's not also u-url.

**Comment by pfefferle** [comment]
@snarfed I understand the issue with the ActivityPub URL, but I am mainly talking about the target URL.

```HTML
<article class="u-repost-of h-cite">
  <span class="p-uid">https://notiz.blog/2023/04/03/aufkleber/</span>
</article>
```

If this does not use the URL, we have no proof that this is the correct target. Let's assume, there are more than one reply-ofs on this site. In the worst case we have to check every property and that makes microformats parsing even worse.

😥

**Comment by dshanske** [comment]
> u-uid on these posts points to the JSON AS2 activity, not a human-readable HTML page, which is why it's not also u-url.

In the repost-of, you use uid when referring to notiz.blog. That is an HTML readable page, so I would make it u-url.

I can see your point that maybe indieweb.social is a uid, because it is pointing to the other version of it.

Is the issue on your side that the WordPress activitypub plugin will return either AS2 or HTML?

**Comment by snarfed** [comment]
> @snarfed I understand the issue with the ActivityPub URL, but I am mainly talking about the target URL.

Ahh true! That does need u-url, I'll add it.

**Comment by pfefferle** [comment]
@dshanske the plain text is fine if @snarfed adds `p-url`.

@dshanske that has nothing to do with the WordPress plugin!

@snarfed Maybe we could also find a way to have a source URL, otherwise we have to use the brid.gy URL and that might break over time. And we can not find out if it is a dupe from a Webmention for example.

**Comment by pfefferle** [comment]
But because @snarfed mentioned the post-type discovery algo and there really seems to be no requirement, I tried to make the parser work with the actual code of fed.brid.gy. Seems to work with all examples so far. Not sure if it breaks something though. Maybe you both (@snarfed and @dshanske) could have a look: https://github.com/pfefferle/wordpress-webmention/pull/392

**Comment by snarfed** [comment]
> Maybe we could also find a way to have a source URL, otherwise we have to use the brid.gy URL and that might break over time.

Sure! I don't know what other URL to use though. Got any ideas?

**Comment by pfefferle** [comment]
I assume, that the items in my mastodon outbox are the same that are sent via federation, so every "object" has an URL that is actually the permalink of the post:

```JSON
{
      "id": "https://mastodon.social/users/pfefferle/statuses/110243150222171184/activity",
      "type": "Create",
      "actor": "https://mastodon.social/users/pfefferle",
      "published": "2023-04-22T15:22:54Z",
      "object": {
        "id": "https://mastodon.social/users/pfefferle/statuses/110243150222171184",
        "type": "Note",
        "summary": null,
        "inReplyTo": "https://cosocial.ca/users/evan/statuses/110243139204372951",
        "published": "2023-04-22T15:22:54Z",
        "url": "https://mastodon.social/@pfefferle/110243150222171184",
        "attributedTo": "https://mastodon.social/users/pfefferle",
        "to": [
          "https://www.w3.org/ns/activitystreams#Public"
        ]
      }
    }
```

You seem to use the ID fiels and that is really only a `uid`.

**Comment by snarfed** [comment]
Many AS2 activities do have `url`s, you're right, but not all. Specifically, here we're discussing Mastodon's AP `Announce` activities for reposts, and those don't have `url`. Here's a recent `Announce` from your inbox:

```json
{
   "actor" : "https://mastodon.social/users/pfefferle",
   "cc" : [
      "https://econtwitter.net/users/osc",
      "https://mastodon.social/users/pfefferle/followers"
   ],
   "id" : "https://mastodon.social/users/pfefferle/statuses/110230098546181336/activity",
   "object" : "https://econtwitter.net/users/osc/statuses/110229703334316885",
   "published" : "2023-04-20T08:03:42Z",
   "to" : [
      "https://www.w3.org/ns/activitystreams#Public"
   ],
   "type" : "Announce"
}
```

Bridgy Fed definitely does propagates the AS2 `url` into mf2 `u-url` if it's available! Here's how it converts your example reply `Create` above, with `u-url`: https://granary.io/url?input=as2&output=html&url=https%3A%2F%2Fmastodon.social%2Fusers%2Fpfefferle%2Fstatuses%2F110243150222171184%2Factivity :

```html
<article class="h-entry">
  <span class="p-uid">https://mastodon.social/users/pfefferle/statuses/110243150222171184</span>
  <time class="dt-published" datetime="2023-04-22T15:22:54Z">2023-04-22T15:22:54Z</time>

  <span class="p-author h-card">
    <data class="p-uid" value="https://mastodon.social/users/pfefferle"></data>
    <a title="mastodon.social/users/pfefferle" class="u-url" href="https://mastodon.social/users/pfefferle">mastodon.social/users/pfefferl...</a>
  </span>

  <a title="mastodon.social/@pfefferle/110243150222171184" class="u-url" href="https://mastodon.social/@pfefferle/110243150222171184">mastodon.social/@pfefferle/110...</a>
  <div class="e-content p-name">

  <p><span class="h-card"><a href="https://cosocial.ca/@evan" class="u-url mention">@<span>evan</span></a></span> <span class="h-card"><a href="https://manton.org/activitypub/manton" class="u-url mention">@<span>manton</span></a></span> i am also curious about that. Would love to have that in the WP plugin too!</p>
<a class="u-mention" aria-hidden="true" href="https://cosocial.ca/users/evan"></a>
<a class="u-mention" aria-hidden="true" href="https://manton.org/activitypub/manton"></a>
  </div>

  <a class="u-in-reply-to" href="https://cosocial.ca/users/evan/statuses/110243139204372951"></a>
</article>
```

**Comment by pfefferle** [comment]
Hmmm... Seems that I have to re-think what to do in this case! Because linking to the fed.brid.gy html site seems no good idea!
