### ISSUE TITLE
HackerNews links don't work

### ISSUE THREAD

**Issue by edent** [pfefferle/wordpress-webmention#393]
Tried to submit https://news.ycombinator.com/item?id=35927509 to https://shkspr.mobi/blog/2023/05/the-new-zip-tld-is-going-to-cause-some-problems/

I got the error

> Not enough data available

**Comment by dshanske** [comment]
You are right, but there isn't enough data. We may have to figure out how to find some.

**Comment by edent** [comment]
Same issue on Lemmy - for example https://lemmy.one/post/78196

**Comment by dshanske** [comment]
Anyone want to read the HTML and see if there is something we can extract of any type?

**Comment by edent** [comment]
@pfefferle I was submitting them manually to my site.  That's where I saw the error.

Looking through the HTML of both HN & Lenny, I can see the links to my site. Is there something specific I should be looking for?

**Comment by pfefferle** [comment]
There is a bug in 5.0.0 that does not parse the meta-headers correctly. Maybe we wait until 5.1.0 is released to re-check.

**Comment by dshanske** [comment]
It's still a problem of what data could we extract to render a preview.

**Comment by janboddez** [comment]
Sorry to chime in like this. :-S That's what IndieBlocks does, too. Set a default name (either "Anonymous" or the page's host name) and content. Then if there are microformats, we turn those into something more meaningful.

Shouldn't be to hard to do something similar here. I'd be happy to look into it, and maybe submit a PR.

**Comment by pfefferle** [comment]
Maybe use the domain host?

**Comment by edent** [comment]
Also, LinkedIn (urgh!). Take a URl like this - https://www.linkedin.com/posts/terenceeden_why-im-using-mx-as-a-title-activity-7074702026084884480-jO0C?utm_source=share&utm_medium=member_desktop

It doesn't contain the direct link in the HTML, but it is in the JSON+LD as "sharedContent":

```
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "SocialMediaPosting",
  "@id": "https://www.linkedin.com/posts/terenceeden_why-im-using-mx-as-a-title-activity-7074702026084884480-jO0C",
  "author": {
    "name": "Terence Eden",
    "image": {
      "url": "https://media.licdn.com/dms/image/C4E03AQEX11qBnAo43A/profile-displayphoto-shrink_400_400/0/1517677542848?e=1692230400&v=beta&t=-AHOoj__Ehm_p24dQ6McPbqNj9gQ2UsjvzOCIU16IGs",
      "@type": "ImageObject"
    },
    "url": "https://uk.linkedin.com/in/terenceeden",
    "@type": "Person"
  },
  "datePublished": "2023-06-14T11:00:04.600Z",
  "image": {
    "url": "https://media.licdn.com/dms/image/sync/D5627AQHWF4nuGqlfzQ/articleshare-shrink_800/0/1686397225711?e=1687428000&v=beta&t=SsQ_1b8M3xAGXnhUvID0976rpItlTLdC2Gz9RG3sXwI",
    "@type": "ImageObject"
  },
  "sharedContent": {
    "@type": "WebPage",
    "headline": "Why I'm using \"Mx\" as a title",
    "url": "https://shkspr.mobi/blog/2023/06/why-im-using-mx-as-a-title/"
  },
  "articleBody": "What title do you use when filling in forms? Mr? Mrs? Ms? Or something newer and more incluside?\n\nWhy do companies want to know my title? What are they going to do with my data?\n\nHere's why I'm using \"Mx\" as my title.\nhttps://lnkd.in/eCNH5sqp",
  "isAccessibleForFree": false,
  "hasPart": {
    "@type": "WebPageElement",
    "isAccessibleForFree": false,
    "cssSelector": ".details"
  }
}
</script>
```

**Comment by pfefferle** [comment]
The JSON-LD parser had a bug, but should work with the latest PR.

**Comment by edent** [comment]
Cool! When there's a new release I'll give it a go and report back.

Thanks for all your work on this.

**Comment by edent** [comment]
@pfefferle LinkedIn is now working - thanks :-)

**Comment by dshanske** [comment]
There's always the API.  https://github.com/HackerNews/API

**Comment by pfefferle** [comment]
But I wouldn't see that as part of the plugin! that's too specific! 😳

Any ideas what we could add to make Hackernews at least pingable and not looking too ugly?

**Comment by edent** [comment]
Grabbing the text from the `<title>` element seems like the easiest solution to me. Or use the domain name as a fallback?

**Comment by pfefferle** [comment]
Result is now

```JSON
{
  "published": {
    "date": "2023-12-28 19:41:45.864580",
    "timezone_type": 3,
    "timezone": "UTC"
  },
  "url": "https://news.ycombinator.com/item?id=35927509",
  "author": {
    "type": "card",
    "name": "news.ycombinator.com"
  },
  "name": "The new .zip TLD is going to cause some problems | Hacker News",
  "site_name": "news.ycombinator.com",
  "content": "The new .zip TLD is going to cause some problems | Hacker News",
  "response_type": "mention",
  "raw": {
    "referrer": "origin",
    "viewport": "width=device-width, initial-scale=1.0"
  }
}
```
