### ISSUE TITLE
It looks like facepile can not be seen on block themes

### ISSUE THREAD

**Issue by Guanchishan** [pfefferle/wordpress-webmention#394]
Please see https://sanguok.com/en/microblog/bfda08ebf4/ 
![image](https://github.com/pfefferle/wordpress-webmention/assets/30859354/a78ec189-f6c3-435b-a60c-fc691f503e7f)

The theme on my WordPress blog is Zoologist, but the theme "2023" also not show facepile. They are all block themes.

I have also made the relevant settings:
![image](https://github.com/pfefferle/wordpress-webmention/assets/30859354/2a874ab1-3066-4dd1-a969-50a40cbfba41)

Thank you very much.

**Comment by pfefferle** [comment]
Yes, sadly all current comment blocks seem to ignore all classic possibilities to filter and modify the comment section :(

**Comment by Guanchishan** [comment]
> Yes, sadly all current comment blocks seem to ignore all classic possibilities to filter and modify the comment section :(

So sorry :( but still thank you for telling me.

**Comment by pfefferle** [comment]
That said, it is not impossible, but we need some help with a Webmention block, that might add the functionality for block-themes.

**Comment by pfefferle** [comment]
should work now!
