### ISSUE TITLE
Undo "Approve & Always Allow"?

### ISSUE THREAD

**Issue by edent** [pfefferle/wordpress-webmention#395]
I accidentally clicked the "Approve & Always Allow" option next to a comment. Is there any way I can undo that action?

I can't find anything in the settings, and manually unapproving comments is time consuming.

Is there a database option I can fiddle with?

**Comment by dshanske** [comment]
Ot needs to be updated, but it adds it to the list of approved domains

**Comment by edent** [comment]
Ah! It's in "IndieWeb > Webmention > Automatically approve Webmention from these domains"

Thanks

**Comment by dshanske** [comment]
I have thoughts of changing it to author URL because it could be used to automatically approve all Bridgy sent mentions from a single mastodon instance.

**Comment by edent** [comment]
Yes, that's what happened to me. Every single think from Bridgy was appearing.

**Comment by dshanske** [comment]
I wrote the code for that feature in 2018. It was a more innocent time
