### ISSUE TITLE
Avatar overlaps text in Dashboard widget

### ISSUE THREAD

**Issue by janboddez** [pfefferle/wordpress-webmention#396]
There's a `<div class="dashboard-comment-wrap has-row-actions">` in there, which would need a `has-avatar` class ...

<img src="https://github.com/pfefferle/wordpress-webmention/assets/8428432/3931e52f-6677-472c-85fb-926a3f3e4ccb" width="400">

Not sure if I'm the only one seeing this?

The second mention looks okay because as far as WordPress is concerned, it's just a comment (its comment type is empty).

**Comment by janboddez** [comment]
The issue is in WordPress core. For comments with a type that is non-empty and not `comment`, `has-avatar` is simply not added, even if there happens to be one: https://github.com/WordPress/WordPress/blob/f6ee7d285f8cd9568adcebd27a3ae24ae26c7c73/wp-admin/includes/dashboard.php#L887

There doesn't seem to be a way to filter the HTML output, so the only way to fix this would be (1) custom CSS, or (2) create a WP core issue. I don't think very many plugins use `comment_type` at all, so they may simply not be aware.

**Comment by janboddez** [comment]
In this particular case, adding something like the following does the trick:
```
.bookmark .dashboard-comment-wrap {
	padding-inline-start: 63px;
}
```
Could probably expand that to likes, favorites, reads, and reposts (and any other comment types that aren't `comment`/empty).

**Comment by pfefferle** [comment]
would you like to make a PR for that @janboddez ?

**Comment by janboddez** [comment]
I this is still an issue, yes.

Ideally, this would be addressed in core; I simply think no one really uses comment types. Except for pingback and so on, but those _never_ have an avatar.

Ideally, we'd load this as a seperate stylesheet (which I think is still the preferred way, for now) and only on the Dashboard page.
