### ISSUE TITLE
Add native support for exotic webmentions

### ISSUE THREAD

**Issue by peterwilsoncc** [pfefferle/wordpress-webmention#40]
Follow up to #22.

Support webmentions natively on the following page types:
- Blog listing (is_home)
- Archive pages (is_archive)
  - Author
  - Date
  - taxonomies (categories, tags, etc)
  - custom post type full archives

Archives could be considered a single page, even though they can span multiple pages. 

Implementation brain storming:
- Create unlisted custom post type to store mentions against, `webmention_exotic`?
- home page post is created on activating the plugin
- archives, etc have the custom post created on receiving the first web mention
- Using the standard comment command will need a little work as the first thing it does is check it's on a singular
- themes would need to be modified to support it, plugin doesn't assume, `add_theme_support( 'exotic-webmentions')` could be suitable

**Comment by singpolyma** [comment]
at least mentions on homepage and author pages would be nice.

**Comment by dshanske** [comment]
We can also extend the existing support for setting a default page id to be a bit more complex as a simpler measure.

**Comment by dshanske** [comment]
There was an idea proposed of having a separate endpoint for these pages that is intriguing.

**Comment by dshanske** [comment]
I think that the recent move of the filter outside the receiver so that it can be called by an external function is the best that will be done for the foreseeable future. I have an idea for an extension that would create a hidden custom post type to store comments for exotic pages. But for now, I would suggest closing this.

**Comment by pfefferle** [comment]
should this still be part of the core plugin?

**Comment by gRegorLove** [comment]
I ran into this when manually sending a homepage webmention to @snarfed:
`curl -i -d source=https://gregorlove.com/2017/04/snarfed.org-can-you-help-with/ -d target=https://snarfed.org/ https://snarfed.org/wp-json/webmention/1.0/endpoint`

Response:
`{"code":"source_equals_target","message":"Target and source cannot direct to the same resource","data":{"status":400}}`

**Comment by tantek** [comment]
This sounds like a multi-part issue that should be broken out into individual issues that have specific use-cases that justify them, and then close this one.

E.g. 
* Issue #60 - use-cases: http://indieweb.org/homepage#Webmention_to_homepage (sufficient to justify incorporating this functionality into the core plugin)

What are the use-cases for sending (and receiving) webmentions to archive pages?

**Comment by dshanske** [comment]
We have homepage mention support as a feature now. @peterwilsoncc Would you weigh in on original intent, otherwise maybe we should close this.

**Comment by peterwilsoncc** [comment]
@dshanske happy for it to be closed off. I can't think of a suitable use case for including it on archive pages.
