### ISSUE TITLE
Comment form issue using block theme

### ISSUE THREAD

**Issue by janboddez** [pfefferle/wordpress-webmention#404]
After updating to v5.1.0, I get this error in my debug.log:
```
File Theme without comments.php is deprecated since version 3.0.0 with no alternative available. Please include a comments.php template in your theme.
```
I'm also suddenly seeing the comment form _twice_.

Disabling the plugin fixes both. I'm 99% sure it has to do with me using a _block theme_.

**Comment by janboddez** [comment]
The Gutenberg dynamic comments block has this here code in it, to, I believe, work around the notice.
```
/*
	 * There's a deprecation warning generated by WP Core.
	 * Ideally this deprecation is removed from Core.
	 * In the meantime, this removes it from the output.
	 */
	add_filter( 'deprecated_file_trigger_error', '__return_false' );
	comments_template();
	remove_filter( 'deprecated_file_trigger_error', '__return_false' );
```
I've been looking for the code that may be calling `comments_template()`, can't readily find it. I'll try to dig a bit deeper.

**Comment by janboddez** [comment]
So, everything works if I just disable "Separate Webmention Types from Comments." Which I can, because I'm doing this separately anyhow.

Update: Could be this is the issue: https://github.com/pfefferle/wordpress-webmention/blob/6e4ed42bea05966ba85e4b05399348ea382ea951/templates/webmention-comments.php#L37

Block themes don't have a `comments.php`.

A fix _might_ be (just guessing here) to instead call code above, same way Gutenberg does it.

**Comment by janboddez** [comment]
Thinking it might habe been introduced here: https://github.com/pfefferle/wordpress-webmention/commit/5d41744fe7405a5d723dc167646b72050923e3c3

Webmention used to filter the `comment_template` (which I believe block themes _normally_ don't call, at all). Whereas now, the template seems to be called always (through `comment_form_before`).

**Comment by janboddez** [comment]
OK, so what's happening is the `core/post-comments-form` block calls `comment_form()` which calls `comment_form_before` which loads the facepile template, which calls `locate_template( 'comments.php' )`.

But because block themes don't have it, it instead returns `wp-includes/theme-compat/comments.php`, which calls ... `comment_form()`.

I don't yet understand why "classic" themes don't suffer from this.

**Comment by janboddez** [comment]
Looks like I'm not the only one experiencing this: https://cagrimmett.com/week-of/2023/06/11/week-of-june-5-2023/

**Comment by janboddez** [comment]
The following (in `webmention-comments.php`) works for me:
```
if ( ! wp_is_block_theme() ) :
	load_template( locate_template( 'comments.php' ) );
endif;
```

**Comment by pfefferle** [comment]
thanks a lot for your debugging! do you want to file a PR for that change?

**Comment by janboddez** [comment]
I'll give it a try later today!

The one thing I haven't yet figured out is why classic themes don't suffer from this.

If a theme's `comments.php` calls `comment_form()` which via the `before_comment_form` hook again includes ... the theme's `comments.php` (or the fallback version in `wp-includes`), wouldn't you also end up in a sort of loop?

In fact, it would seem that `load_template( locate_template( 'comments.php' ) );` isn't really needed, ever. Classic themes always call `comment_form()` (I think!)  from a `comments.php` template. And when `comment_form()` resumes, after having run the `before_comment_form` callbacks, it _will already_ display the form and so on.
