### ISSUE TITLE
error on webmention page in dashboard

### ISSUE THREAD

**Issue by troutcolor** [pfefferle/wordpress-webmention#406]
I just updated to 5.1.0 having skipped

I get:
Fatal error: Maximum execution time of 30 seconds exceeded in /Customer_web_sites/johnjohnston/public_html/blog/wp-includes/class-wpdb.php on line 2431

tring to get to the setting page. 

I did get a mention, from micro.bog, since updating.

Cheers
John

**Comment by dshanske** [comment]
That's the upgrade for the missing author data.

**Comment by troutcolor** [comment]
> That's the upgrade for the missing author data.

Thanks, is there anything I can do about it?

**Comment by dshanske** [comment]
Up your maximum execution time and I'll see about batch upgrade functionality.

**Comment by troutcolor** [comment]
Thanks, I'll ask my host. 

Cheers

John

**Comment by dshanske** [comment]
Still going to try to batch it..not everyone can do that. Also, after it runs, you can reset to 30

**Comment by troutcolor** [comment]
Will done thanks

cheers

John

**Comment by pfefferle** [comment]
is this still an issue, or was it only a hickup of the migration?

**Comment by troutcolor** [comment]
> is this still an issue, or was it only a hickup of the migration?

Well I've not seen any problem with it since and I seem to have set time limit back to 30 and everything has been smooth enough for me to forget about it;-)

**Comment by pfefferle** [comment]
no problem ☺️
