### ISSUE TITLE
"Initial number of faces to show in facepiles" setting no longer works in 5.x

### ISSUE THREAD

**Issue by snarfed** [pfefferle/wordpress-webmention#417]
Hi all! I'm late to actually upgrading, but the v5.0 plugin merge is great. Thank you again!

The only problem for me so far is that it broke this setting:

<img width="661" alt="image" src="https://github.com/pfefferle/wordpress-webmention/assets/778068/f84cab88-2243-4d7e-835a-afbe72140848">

I set it to 10, but it has no effect. Facepiles aren't truncated to the first 10; they render all faces. @pfefferle confirmed in #indieweb-wordpress yesterday that this was a known issue: "Yes, with the new templating it is a bit more complex to do :disappointed:." @dshanske any idea how you all could fix this?

**Comment by dshanske** [comment]
I'll have a look...been behind lately.

**Comment by dshanske** [comment]
Merged in #424
