### ISSUE TITLE
How to have webmention without XML-RPC open?

### ISSUE THREAD

**Issue by bixfrankonis** [pfefferle/wordpress-webmention#425]
So I know [this is closed](https://github.com/pfefferle/wordpress-webmention/issues/36) but it's not clear to me anything really came of that discussion.

I do not want XML-RPC open on my site at all. But even if I have trackbacks and pingbacks disabled in site settings, and XML-RPC turned off by custom function, if I'm understanding things correctly, for this plugin to work accepting pings needs to be set on posts themselves.

But that then means on every post I've got an XML-RPC endpoint exposed due to pingbacks.

There's got to be a way to do webmentions without requiring XML-RPC to be open. Please?

Please?

**Comment by dshanske** [comment]
Are you fine with every post accepting webmentions?

**Comment by dshanske** [comment]
The reason I'm asking is we can do a quick fix in that direction and work on something more granular in the long-term.
