### ISSUE TITLE
Sanity check send_webmentions() in class-sender.php

### ISSUE THREAD

**Issue by shawfactor** [pfefferle/wordpress-webmention#447]
I'd suggest a sanity check that the post still exists in the function, something like:

if ( FALSE === get_post_status( $post_id  ) ) {
  // The post no longer exists so lets early return
return;
}

This is because if the post ceases to exist in the interim (e'g. between the publish and sending) a fatal error is generated.

**Comment by dshanske** [comment]
Has that actually happened?

**Comment by shawfactor** [comment]
I see it happening all the time in my logs just after I trash then deleted
certain custom post types. I think. The plugins tries to notify other sites
that the cpt has been deleted but the cpt is no longer in the db when the
cron is processed.

Pete
