### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: DOMXPath

### ISSUE THREAD

**Issue by cybeardjm** [pfefferle/wordpress-webmention#452]
Just found multiple occurences of this error in my PHP error log

[28-Dec-2023 18:34:10 UTC] PHP Fatal error:  Uncaught TypeError: DOMXPath::__construct(): Argument #1 ($document) must be of type DOMDocument, WP_Error given in /srv/data/web/vhosts/www.didiermary.fr/htdocs/wp-content/plugins/webmention/includes/class-response.php:256
Stack trace:
#0 /srv/data/web/vhosts/www.didiermary.fr/htdocs/wp-content/plugins/webmention/includes/class-response.php(256): DOMXPath->__construct()
#1 /srv/data/web/vhosts/www.didiermary.fr/htdocs/wp-content/plugins/webmention/includes/class-response.php(336): Webmention\Response->get_html_links()
#2 /srv/data/web/vhosts/www.didiermary.fr/htdocs/wp-content/plugins/webmention/includes/class-discovery.php(176): Webmention\Response->get_links_by()
#3 /srv/data/web/vhosts/www.didiermary.fr/htdocs/wp-content/plugins/webmention/includes/functions.php(272): Webmention\Discovery::discover_endpoint()
#4 /srv/data/web/vhosts/www.didiermary.fr/htdocs/wp-content/plugins/webmention/includes/class-sender.php(104): webmention_discover_endpoint()
#5 /srv/data/web/vhosts/www.didiermary.fr/htdocs/wp-content/plugins/webmention/includes/class-sender.php(181): Webmention\Sender::send_webmention()
#6 /srv/data/web/vhosts/www.didiermary.fr/htdocs/wp-content/plugins/webmention/includes/class-sender.php(299): Webmention\Sender::send_webmentions()
#7 /srv/data/web/vhosts/www.didiermary.fr/htdocs/wp-includes/class-wp-hook.php(324): Webmention\Sender::do_webmentions()
#8 /srv/data/web/vhosts/www.didiermary.fr/htdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#9 /srv/data/web/vhosts/www.didiermary.fr/htdocs/wp-includes/plugin.php(565): WP_Hook->do_action()
#10 /srv/data/web/vhosts/www.didiermary.fr/htdocs/wp-cron.php(191): do_action_ref_array()
#11 {main}
  thrown in /srv/data/web/vhosts/www.didiermary.fr/htdocs/wp-content/plugins/webmention/includes/class-response.php on line 256

**Comment by pfefferle** [comment]
Should be fixed with my latest changes
