### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string (line 782)

### ISSUE THREAD

**Issue by cybeardjm** [pfefferle/wordpress-webmention#460]
Hi @pfefferle - a new error appeared in my PHP errorlog, on a different line from last time.

[06-Mar-2024 02:09:15 UTC] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-content/plugins/webmention/includes/Handler/class-mf2.php:782
Stack trace:
#0 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-content/plugins/webmention/includes/Handler/class-mf2.php(55): Webmention\Handler\MF2->get_response_type()
#1 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-content/plugins/webmention/includes/class-handler.php(84): Webmention\Handler\MF2->parse()
#2 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-content/plugins/webmention/includes/class-receiver.php(657): Webmention\Handler->parse_aggregated()
#3 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-includes/class-wp-hook.php(324): Webmention\Receiver::default_commentdata()
#4 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#5 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-content/plugins/webmention/includes/class-receiver.php(329): apply_filters()
#6 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-includes/rest-api/class-wp-rest-server.php(1193): Webmention\Receiver::post()
#7 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-includes/rest-api/class-wp-rest-server.php(1041): WP_REST_Server->respond_to_request()
#8 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-includes/rest-api/class-wp-rest-server.php(431): WP_REST_Server->dispatch()
#9 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-includes/rest-api.php(424): WP_REST_Server->serve_request()
#10 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-includes/class-wp-hook.php(324): rest_api_loaded()
#11 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#12 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-includes/plugin.php(565): WP_Hook->do_action()
#13 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-includes/class-wp.php(418): do_action_ref_array()
#14 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-includes/class-wp.php(813): WP->parse_request()
#15 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-includes/functions.php(1336): WP->main()
#16 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-blog-header.php(16): wp()
#17 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/index.php(17): require('...')
#18 {main}
  thrown in /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-content/plugins/webmention/includes/Handler/class-mf2.php on line 782

**Comment by pfefferle** [comment]
Thanks for all your debugging!

This should fix the issue!
