### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Attempt to modify property "query_vars" on string

### ISSUE THREAD

**Issue by cybeardjm** [pfefferle/wordpress-webmention#472]
Error appears multiple times in my PHP error_log
IndieBlocks by @janboddez appears on lines 6 / 7 / 8.

PHP Fatal error:  Uncaught Error: Attempt to modify property "query_vars" on string in /srv/data/web/vhosts/[www removed]/htdocs/wp-content/plugins/webmention/includes/class-comment-walker.php:307
Stack trace:
#0 /srv/data/web/vhosts/[www removed]/htdocs/wp-includes/class-wp-hook.php(324): Webmention\Comment_Walker::comment_query()
#1 /srv/data/web/vhosts/[www removed]/htdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#2 /srv/data/web/vhosts/[www removed]/htdocs/wp-includes/plugin.php(565): WP_Hook->do_action()
#3 /srv/data/web/vhosts/[www removed]/htdocs/wp-includes/class-wp-comment-query.php(394): do_action_ref_array()
#4 /srv/data/web/vhosts/[www removed]/htdocs/wp-includes/class-wp-comment-query.php(366): WP_Comment_Query->get_comments()
#5 /srv/data/web/vhosts/[www removed]/htdocs/wp-includes/class-wp-comment-query.php(323): WP_Comment_Query->query()
#6 /srv/data/web/vhosts/[www removed]/htdocs/wp-content/plugins/indieblocks/includes/functions.php(418): WP_Comment_Query->__construct()
#7 /srv/data/web/vhosts/[www removed]/htdocs/wp-content/plugins/indieblocks/blocks/facepile-content/class-facepile-content-block.php(36): IndieBlocks\get_facepile_comments()
#8 /srv/data/web/vhosts/[www removed]/htdocs/wp-includes/class-wp-block.php(463): IndieBlocks\Facepile_Content_Block::render_facepile_content_block()
#9 /srv/data/web/vhosts/[www removed]/htdocs/wp-includes/class-wp-block.php(443): WP_Block->render()
#10 /srv/data/web/vhosts/[www removed]/htdocs/wp-includes/class-wp-block.php(443): WP_Block->render()
#11 /srv/data/web/vhosts/[www removed]/htdocs/wp-includes/blocks/comments.php(40): WP_Block->render()
#12 /srv/data/web/vhosts/[www removed]/htdocs/wp-includes/class-wp-block.php(463): render_block_core_comments()
#13 /srv/data/web/vhosts/[www removed]/htdocs/wp-includes/class-wp-block.php(443): WP_Block->render()
#14 /srv/data/web/vhosts/[www removed]/htdocs/wp-includes/blocks.php(1705): WP_Block->render()
#15 /srv/data/web/vhosts/[www removed]/htdocs/wp-includes/blocks.php(1743): render_block()
#16 /srv/data/web/vhosts/[www removed]/htdocs/wp-includes/blocks/template-part.php(150): do_blocks()
#17 /srv/data/web/vhosts/[www removed]/htdocs/wp-includes/class-wp-block.php(463): render_block_core_template_part()
#18 /srv/data/web/vhosts/[www removed]/htdocs/wp-includes/class-wp-block.php(443): WP_Block->render()
#19 /srv/data/web/vhosts/[www removed]/htdocs/wp-includes/blocks.php(1705): WP_Block->render()
#20 /srv/data/web/vhosts/[www removed]/htdocs/wp-includes/blocks.php(1743): render_block()
#21 /srv/data/web/vhosts/[www removed]/htdocs/wp-includes/block-template.php(260): do_blocks()
#22 /srv/data/web/vhosts/[www removed]/htdocs/wp-includes/template-canvas.php(12): get_the_block_template_html()
#23 /srv/data/web/vhosts/[www removed]/htdocs/wp-includes/template-loader.php(106): include('...')
#24 /srv/data/web/vhosts/[www removed]/htdocs/wp-blog-header.php(19): require_once('...')
#25 /srv/data/web/vhosts/[www removed]/htdocs/index.php(17): require('...')
#26 {main}
  thrown in /srv/data/web/vhosts/[www removed]/htdocs/wp-content/plugins/webmention/includes/class-comment-walker.php on line 307

**Comment by pfefferle** [comment]
what version of the plugin? this should be fixed in the latest version already.

**Comment by cybeardjm** [comment]
I have 5.3.1, but let me check again tomorrow. The errors are dated 05/14, and might have happened right between the 2 updates on the WWW blog (on the second one, I only got the latest update and get no error).

**Comment by pfefferle** [comment]
thanks! yes this was an issue with 5.3.0, maybe you had some errors in the logs because of that.

**Comment by cybeardjm** [comment]
OK, seems good now.

**Comment by pfefferle** [comment]
Then I will close this for now. Feel free to re-open if still a problem!
