### ISSUE TITLE
"No homepage mentions" setting doesn't work?

### ISSUE THREAD

**Issue by snarfed** [pfefferle/wordpress-webmention#490]
Hi guys! I had homepage mentions (#161) set to go to https://snarfed.org/about for a long time. I recently turned them off, ie changed _Set a page for mentions of the homepage to be sent to_ set to _No homepage mentions,_ but they're still getting added to that page: https://snarfed.org/about#comments

Lmk if you need any info from me to help debug!

**Comment by snarfed** [comment]
from @pfefferle in #indieweb-wordpress:

> oh, there is a wp_cache_get
> and we do not reset it after the settings change 🫣

**Comment by pfefferle** [comment]
Your homepage does not longer have the Webmention endpoint listed. @snarfed Is this maybe cached on brid.gy?

**Comment by snarfed** [comment]
Hmm! I removed it a bit ago, and Bridgy only caches webmention endpoints for a couple hours.

**Comment by pfefferle** [comment]
@snarfed and you still have the issue?

**Comment by snarfed** [comment]
Oddly yes, which implies that this wasn't the root problem. Strange.

**Comment by pfefferle** [comment]
But I checked the whole code, this can't work! Can you check for filters you maybe use somewhere?

**Comment by snarfed** [comment]
It's possible this is coming from @-mentions that get sent directly to an h-card's URL directly, and somehow that profile URL for me in some places is `/about` instead of `/`. I'm not sure exactly, and I may not be able to dig into it soon. If you all don't think there's a plugin bug here, even including the `wp_cache_get` call that might need to be reset, feel free to close this.

**Comment by pfefferle** [comment]
I Even checked the cache and it is bypassed by the setting!

**Comment by snarfed** [comment]
Ok! Let's close for now then.
