### ISSUE TITLE
Notification mails messed up since 2.4.0

### ISSUE THREAD

**Issue by pep-** [pfefferle/wordpress-webmention#51]
Since the last release, the notification mails sent by Wordpress are compelete messed up. As the blog admin, I get empty mails like this:

> Ein neuer Kommentar zum Beitrag „“ wartet auf deine Freigabe
> 
> Autor:  (IP: , )
> E-Mail:
> URL:
> Kommentar:

while the post author gets mails that contain the entire article in the "Comment:" field ("Kommentar" in the above quote). With the previous version, notifications worked fine.

**Comment by pfefferle** [comment]
I've only changed version numbers and coding styles, so this might be a problem of the latest semantic linkbacks plugin?!?

**Comment by armingrewe** [comment]
Can't confirm that for me, on my blog it works fine. It's actually better than before, as it now gives me the name in the email (previously it just said "Bridgy response").

**Comment by pep-** [comment]
@pfefferle Yes, it might be the semantic-linkbacks plugin as that was updated at the same time. Can you move the issue?

**Comment by pfefferle** [comment]
@pep- Github doesn't allow moving tickets... can you just copy&paste it?

**Comment by pfefferle** [comment]
@armingrewe are you using the latest version of both plugins?

**Comment by armingrewe** [comment]
Yes, installed both last night

**Comment by pfefferle** [comment]
hmmm... perhaps it is a runtime problem...
