### ISSUE TITLE
Support for Deleting Webmentions

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-webmention#52]
https://indiewebcamp.com/delete 

This would require the plugin to recognize the 410 status code as a delete of the post.

**Comment by pfefferle** [comment]
Good idea!

**Comment by dshanske** [comment]
The code in PR #100 returns the 410 and 452 status, but does not yet do anything with them.

**Comment by pfefferle** [comment]
@dshanske I know that you do prefer single, more monolith plugins, but I have made a 410 one anyways https://github.com/indiewordpress/wordpress-deleted-posts

Do you think this should be part a direct feature of the webmention plugin?
