### ISSUE TITLE
Missing some webmentions from brid.gy

### ISSUE THREAD

**Issue by singpolyma** [pfefferle/wordpress-webmention#54]
Problem description: https://github.com/snarfed/bridgy/issues/507

brid.gy got a 200 from me, but the comment is nowhere to be found on my wordpress dashboard. Any ideas where to look?

**Comment by dshanske** [comment]
Wonder if it is worth having a log/debug feature.

A debug feature could write to the server error log if WP_DEBUG is set.

**Comment by singpolyma** [comment]
I'm not sure how the `/comment-page-/#comment-` could even have come out of this plugin...

**Comment by singpolyma** [comment]
That is the output generated by `get_comment_link(0)`

So... perhaps wp_new_comment is failing?

**Comment by singpolyma** [comment]
I'm going to try changing the bottom of my `default_request_hander` to this:

```
                if ( $comment_ID ) {
                        // set header
                        status_header( apply_filters( 'webmention_success_header', 200 ) );

                        // render a simple and customizable text output
                        echo apply_filters( 'webmention_success_message', get_comment_link( $comment_ID ) );

                        do_action( 'webmention_post', $comment_ID );
                } else {
                        status_header( 500 );
                        $wpdb->print_error();
                }
```

and see what happens

**Comment by pfefferle** [comment]
any new findings?

**Comment by pfefferle** [comment]
I will close this for now... please re-open if it still exists...
