### ISSUE TITLE
Support homepage mentions

### ISSUE THREAD

**Issue by singpolyma** [pfefferle/wordpress-webmention#60]

**Comment by dshanske** [comment]
The plugin does allow this, but you have to select the page to represent the homepage

**Comment by singpolyma** [comment]
Where is this setting?  I don't see a settings page for the webmention plugin on my blog...

**Comment by dshanske** [comment]
It is done as a filter. I would suggest it becomes a setting

**Comment by singpolyma** [comment]
The `webmention_post_id` filter?  I see it now.  Yeah, a setting would be nice, but this will work for now.  Thanks :)

**Comment by dshanske** [comment]
There is opportunity for improvement for newbies. A filter is only useful for the more tech inclined

**Comment by dshanske** [comment]
Technically this is a duplicate with #40 as they cover similar ground.

**Comment by pfefferle** [comment]
https://github.com/pfefferle/wordpress-webmention/issues/60

**Comment by tantek** [comment]
I suggest re-opening this, as a specific issue that has known use-cases.

**Comment by pfefferle** [comment]
added by @dshanske thanks!
