### ISSUE TITLE
Reduce the Number of Filters

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-webmention#70]
I think the defaults for the title and content could be better handled off of preprocess_comment to replace the defaults for new comments now that, in an alternate pull request, the source is passed in the comment array.

For existing comments, we can add a similar filter on the update side.

**Comment by pfefferle** [comment]
I think this is done with the latest changes. Perhaps we should provide a `deprecated.php` file, that keeps the filters for at least one or two new versions.
