### ISSUE TITLE
Safe Remote Get, Valid URLs

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-webmention#72]
I was looking at switching wp_remote_get to wp_safe_remote_get for additional reasons of safety.

The difference between the two appears to be that the 'safe' version runs URLs through wp_http_validate_url(https://developer.wordpress.org/reference/functions/wp_http_validate_url/).

This checks to see if the URL is a valid protocol, restricts ports to 80, 443, 8080 and rejects any URL with a :#?[] in it.

PIngbacks on WordPress currently filter the source URL through wp_http_validate_url. 

Opening this to discuss if this change makes sense. Do we want to limit in this way?

**Comment by dshanske** [comment]
This is related to the recent PR #100 that does use the safe version. But the requirement in the specification says it should reject localhost and other options. Using this would be consistent with WordPress security intent.

**Comment by pfefferle** [comment]
done!
