### ISSUE TITLE
Retrieve Self Pings Directly

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-webmention#73]
Is it better to identify self-pings and, instead of retrieving them via HTTP, retrieve them by getting the Post ID and pulling the content directly?

In this proposal, if the handler identifies that the source URL is on the same site, it would call a second function that would generate the comment from the local URL.

Unsure of how this would affect Semantic Linkbacks integration.

**Comment by pfefferle** [comment]
I think adds a lot of complexity for very little improvement.

**Comment by dshanske** [comment]
That was my thinking, but I want to explore every opportunity for improvement. That is why I am brainstorming in the issues tracker.
