### ISSUE TITLE
User Agent and Headers for Remote Get

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-webmention#74]
Pingback sets the user-agent to, by default, for example: WordPress/4.5;http://www.example.com; verifying pingback from 0.0.0.0.

And it passes the X-Pingback-Forwarded-For header with the remote ip of where the request came from.

    $user_agent = apply_filters( 'http_headers_useragent', 'WordPress/' . $wp_version . '; ' . get_bloginfo( 'url' ) );
        'user-agent' => "$user_agent; verifying pingback from $remote_ip",
        'headers' => array(
            'X-Pingback-Forwarded-For' => $remote_ip,

We should definitely set a user agent as a good citizen, as it defaults to nothing right now. I'm proposing matching the Pingback syntax unless there is some other way to address.

As for the X-Pingback-Forwarded-For, adding this would allow spam filtering by WordPress plugins currently filtering pingbacks, however, I think that could be equally dangerous as Akismet thinks all pingbacks are spam, for example.

**Comment by voxpelli** [comment]
Related discussion around the forward header: http://indiewebcamp.com/Webmention-brainstorming#using_x-forwarded-for_to_mitigate_DDoS_abuse

And regarding the user-agent header, that's a pretty weird user-agent, it doesn't really conform to the format defined by: https://tools.ietf.org/html/rfc7231#section-5.5.3

According to that format the user agent should be something like `WordPressWebmention/1.2.3 (http://example.com/url/to/plugin/page) WordPress/4.5` and probably not include any data related to the specific request. As the user agent stirngsshould identify the user agent any request unique data in them makes it hard to identify the user agent across requests. Better to just add such data in eg. forward headers,

**Comment by dshanske** [comment]
Should it be the plugin url or the site url for the requesting site?

**Comment by voxpelli** [comment]
@dshanske The plugin URL, that way a person can see the code that causes the requests and send improvement requests and bug report to it.

**Comment by dshanske** [comment]
Maybe just WordPress/4.5 webmention.net?

**Comment by voxpelli** [comment]
@dshanske It's supposed to represent the agent in `in decreasing order of their significance for identifying the user agent software` so adding the plugin first and the WordPress version later and specifying the version for both should be enough for a server to pinpoint what version of the agent that was used to make a request to it, and by adding the URL to the plugin page they can also easily find the plugin even if the plugin itself doesn't rank well on Google or something. That's how I think at least :)

**Comment by pfefferle** [comment]
I would say, we should use something like:

`User-Agent: Webmention-Plugin/3.0 WordPress/4.5.2`
