### ISSUE TITLE
failed a couple webmention.rocks tests

### ISSUE THREAD

**Issue by snarfed** [pfefferle/wordpress-webmention#76]
https://webmention.rocks/ is a fun set of tests for webmention clients (ie senders). this plugin passed 19/21 tests when i tried it! congrats!

the two it failed are:

https://webmention.rocks/test/15
This post has a `<link>` tag where the href value is an empty string, meaning the page is its own Webmention endpoint. This tests the relative URL resolver of the sender to ensure an empty string is resolved to the page's URL.

https://webmention.rocks/test/17
This post advertises its Webmention endpoint in an HTML `<link>` tag followed by a later definition in an `<a>` tag. Your Webmention client must only send a Webmention to the one in the `<link>` tag since it appears first in the document.

low priority, of course. thanks!

**Comment by pfefferle** [comment]
oh, thanks for reporting.

**Comment by snarfed** [comment]
looks like https://webmention.rocks/update/1 doesn't quite work either, either step 1 or 2. not sure why. step 1 works ok if i send the webmention manually. i haven't tried step 2 manually yet.

i would guess that the problem is the query param in the webmention endpoint, eg `/update/1/step/1/webmention?key=FmxVbSDfDBzukjG3HwvT`, but this plugin passes https://webmention.rocks/test/21 , which also has a query param in the endpoint, so i don't know.

low priority obviously, just keeping track here.

**Comment by pfefferle** [comment]
Perhaps it is a problem of WordPress' (kinda) async pining?!?

**Comment by pfefferle** [comment]
A note for me: Use https://codex.wordpress.org/Plugin_API/Action_Reference/save_post instead of `publish_post`

**Comment by dshanske** [comment]
I would go with transition_post_status or you will get webmentions sent on draft

**Comment by pfefferle** [comment]
The doku says it is not fired on drafts. `transition_post_status` is only fired if the status changes, so it will not fire if you update a published post, because there is no status change.

**Comment by dshanske** [comment]
I recreated several of the webmention.rocks tests as unit tests to test the endpoint discovery function in the plugin. will eventually recreate them all so they can be run against the function with a single command.

**Comment by pfefferle** [comment]
fixed 15 and 17

**Comment by pfefferle** [comment]
https://webmention.rocks/update/1 is working to with the latest master version

**Comment by pfefferle** [comment]
the update 2 is tricky, because the plugin only sends pings to urls that are in the text... if you remove one, it will not pinged

**Comment by dshanske** [comment]
But WordPress has a list of all the URLs it has previously pinged...we should be able to use that to figure out what links need to be pinged in this case.
