### ISSUE TITLE
Missing escape in regex?

### ISSUE THREAD

**Issue by iamwebrocker** [pfefferle/wordpress-webmention#78]
Hi,

on lines 
[#573](https://github.com/pfefferle/wordpress-webmention/blob/master/webmention.php#L573)
[#578](https://github.com/pfefferle/wordpress-webmention/blob/master/webmention.php#L578)

```
if ( $links = wp_remote_retrieve_header( $response, 'link' ) ) {
			if ( is_array( $links ) ) {
				foreach ( $links as $link ) {
					if ( preg_match( '/<(.[^>]+)>;\s+rel\s?=\s?[\"\']?(http:\/\/)?webmention(.org)?\/?[\"\']?/i', $link, $result ) ) {
						return self::make_url_absolute( $url, $result[1] );
					}
				}
			} else {
				if ( preg_match( '/<(.[^>]+)>;\s+rel\s?=\s?[\"\']?(http:\/\/)?webmention(.org)?\/?[\"\']?/i', $links, $result ) ) {
					return self::make_url_absolute( $url, $result[1] );
				}
			}
		}
```

should the dot in `(.org)?` not be escaped `(\.org)?` ?

Sorry, if I'm wrong, it just jumped on me while I was browsing the code and trying to understand/learn, how I might be fine-tune the way how different incoming types of webmentions may be treated (likes, reposts etc).
thanks for the plugin, it was my entry to the indiewebcamp thing in nuremberg two yrs ago :-)
- Tom

**Comment by pfefferle** [comment]
Oh, you are right! thanks for reporting!

**Comment by pfefferle** [comment]
done by @dshanske
