### ISSUE TITLE
Add Filter to Allow Additional Query Parameters On Webmention Send

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-webmention#86]
'body' => 'source=' . urlencode( $source ) . '&target=' . urlencode( $target )

I want to add a filter here to allow for optional query parameters, such as CSRF and Vouch to be added.

**Comment by pfefferle** [comment]
CRSF and Vouch are query params, and not part of the post body. That means, that you will be able to read these params everywhere you want using `$wp->query_vars`
