### ISSUE TITLE
Add (optional?) logging of success and failures in discovery and pinging

### ISSUE THREAD

**Issue by voxpelli** [pfefferle/wordpress-webmention#89]
Seems like this module has no logging of when things are progressing good or bad or why it's making the decisions that it are etc which makes it somewhat hard to figure why one arrived at a certain outcome after one has already arrived there.

I realized this after having gotten help from @dshanske in pinging me after I deployed a new large release of my Webmention endpoint and when his ping never arrived I wondered what went wrong but considering that there were no logs it would be hard to know if it was the discovery part, the pinging part or something else.

I ended up manually pinging his post to my endpoint and then it worked fine for me, but would have been nicest to have figured out why it didn't work from his WP instance and tried to solve it there instead :)

(My guess in this case is that it maybe could have been a GitHub Pages hiccup or something)

**Comment by dshanske** [comment]
There are four places to log. First, in the server error log, second in a designated log file, three in post meta, four elsewhere in the database.

**Comment by dshanske** [comment]
@petermolnar was commenting on this issue in his WordPress Webmentions plugin.

**Comment by dshanske** [comment]
If we move [webmention_post_send](https://github.com/pfefferle/wordpress-webmention/blob/master/includes/class-webmention-sender.php#L79) out of that conditional, even if the response is null, anyone could add logging to the sending function.

**Comment by dshanske** [comment]
I think we can close this as now possible to log off the hook

**Comment by pfefferle** [comment]
I also added a class for debugging stuff https://github.com/pfefferle/wordpress-webmention/blob/master/includes/debug.php, so I agree with @dshanske
