### ISSUE TITLE
Webmentions not sent for custom post types

### ISSUE THREAD

**Issue by singpolyma** [pfefferle/wordpress-webmention#93]
The issue seems to be that `get_posts( array( 'meta_key' => '_mentionme', 'post_type' => 'any', 'fields' => 'ids', 'nopaging' => true ) )` does not return custom posts.  Even though it says `any` there.

**Comment by dshanske** [comment]
WordPress required unit tests for WP_Query, so it should reveal if any stopped working. So I am stumped.

**Comment by singpolyma** [comment]
When I changed it to say  `array('post', 'actionstream')` it works, but with `any` it does not.

**Comment by dshanske** [comment]
Similar: https://core.trac.wordpress.org/ticket/36824

**Comment by dshanske** [comment]
I want to check out the unit tests for that feature.

**Comment by dshanske** [comment]
I am going to write some tests of my own.

**Comment by dshanske** [comment]
The post type actionstream, is it from a public plugin or something private?

**Comment by singpolyma** [comment]
@dshanske from the diso-actionstream plugin (though I have some local hacks to that for sure).

**Comment by dshanske** [comment]
Did it work when we did a direct database query?

**Comment by singpolyma** [comment]
@dshanske it used to work

**Comment by dshanske** [comment]
So, I need to test this. Will try to figure it out. If it is a Core problem, will revert until fixed.

**Comment by dshanske** [comment]
Still puzzled.

**Comment by dshanske** [comment]
Here's the problem...

‘any‘ – retrieves any type except revisions and types with ‘exclude_from_search’ set to true.

function actionstream_init() {
	register_post_type('actionstream', array(
		'exclude_from_search' => true,
		'publicly_queryable' => true,
		'show_ui' => false,
		'label' => 'Actionstream',
		'taxonomies' => array('post_tag', 'category')
	));
}

**Comment by dshanske** [comment]
https://core.trac.wordpress.org/ticket/17592 - Apparently it was a matter under discussion. Question is...how do we want to address it? For now, we could add a filter that allows custom post types to be expressly added, but it creates extra work. We could revert to directly querying the database...which means we lose the advantages of using WP_Query. 

I think maybe the best way is to call https://codex.wordpress.org/Function_Reference/get_post_types and pass in publicly_queryable = true instead of exclude_from_search = false and get our own list.

**Comment by dshanske** [comment]
@singpolyma Can you change post_type to get_post_types( array( 'publicly_queryable' => true ) and see if that works for you?

**Comment by singpolyma** [comment]
@dshanske yes, that works

**Comment by dshanske** [comment]
I'll write up a PR. Good catch. I'll also update that Core Patch for Pingbacks.
