### ISSUE TITLE
Use New 4.6 Feature for Update Webmention

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-webmention#95]
https://developer.wordpress.org/reference/functions/wp_update_comment/

```
do_action( 'edit_comment', $comment_ID, $data );
```

As of 4.6, you can pass information from the updated comment array into edit_comment. So we can use this for updating webmentions.

**Comment by pfefferle** [comment]
is this fixed now?

**Comment by dshanske** [comment]
Well, we also have the update comment filter committed for 4.7.
