### ISSUE TITLE
Odd webmention with link to bridgy.appspot.com

### ISSUE THREAD

**Issue by chrisaldrich** [pfefferle/wordpress-webmention#97]
Originally filed at https://github.com/snarfed/bridgy/issues/694#issuecomment-241630370, but may be likely caused by WordPress Webmention as bridgy.appspot wasn't/shouldn't have been involved...

I've seen something like this a few times on WordPress (maybe once every thirty webmentions or so), and always presumed it was an issue with my WordPress configuration and processing, but today I saw this with regard to a post on WordPress with a mention of a Known site:

I posted this on WordPress: http://boffosocko.com/2016/08/22/a-new-reading-post-type-for-bookmarking-and-reading-workflow/
which mentioned this post on Known: https://www.rmendes.net/2016/08/22/blockchain-democracy-government-of-the-people-by-the-people-for

The mention appeared on rmendes.net, but had an odd link to brid.gy.appspot.com. See picture below:

![bridgy mention](https://cloud.githubusercontent.com/assets/5882943/17876833/8c1809e2-6892-11e6-9a29-c38c3dccf9b8.PNG)

The brid.gy link was to https://brid-gy.appspot.com/like/facebook/5410052/10101081212777775/10153986333712786
which doesn't relate at all to either the primary post or to the  post that was mentioned. It does however link to another unrelated post on my WordPress site for with a POSSE post to Facebook (for reference, this comment/webmention can be seen at: http://boffosocko.com/2016/08/21/forward-in-pike-position/#comment-31764)

Incidentally, the webmention/comment that appeared on Known didn't include my avatar as it usually would have, but I'm not sure if that's related to the proximal problem, though it may help in troubleshooting. 

If it helps, my webmention should have been sent by the standard WordPress plugin rather than via bridgy publish or other other available methods. I'm also aware that Rick isn't averse to monkeying under the hood of Known, but I suspect that because the mention related to another of my personal posts that POSSEd to Facebook, the fault likely doesn't stem from that.

Any idea what's going on here? I'm at a loss.

Adddendum:
I've also just noticed the **same** bridgy link: https://brid-gy.appspot.com/like/facebook/5410052/10101081212777775/10153986333712786

appear in a webmention from the same originating WP post as above to another WP post on my site that was also referenced (so at least it's being consistent whether the post mentioned was on WP or Known): http://boffosocko.com/2011/05/10/the-adventures-of-sherlock-holmes/#comment-31766

This one , too, choked on providing the correct avatar/site details.

**Comment by pfefferle** [comment]
This is not a problem of the Webmention plugin, but of known. Webmention only sends to links: the source and the target... all the parsing is done by known. See https://github.com/pfefferle/wordpress-webmention/issues/33

**Comment by pfefferle** [comment]
Or it is perhaps a problem of your themes markup.

**Comment by dshanske** [comment]
It wouldn't be his site. Remember that is a Bridgy link, it means that the Bridgy source isn't being successfully parsed for some reason.

**Comment by pfefferle** [comment]
But why is brid.gy involved?

**Comment by dshanske** [comment]
It shows reference to a Facebook like.

**Comment by pfefferle** [comment]
Sure, but there is no brid.gy involved in the Webmention flow, so it can only be a template or parsing problem.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/pfefferle/wordpress-webmention/issues/97" class="u-in-reply-to"></a>I am using uf2 to add microformats, so I thought it could be the case that that is causing a parsing issue (potentially with Jetpack's "Related" plugin, which could be the source for content from another post), but this doesn't seem to be the cause from what I can tell.

Any other particular guesses?

**Comment by pfefferle** [comment]
everything on the known site is ok, except the link, so the Webmention plugin seems to send the correct link. So, as I said, it could ether be a theme problem or a known parsing problem. You have a recent comments section in you sidebar, perhaps known is using one of these links. You said you realized this problem several times... Is it always when mentioning known sites or also other Wordpress sites using Webmention/Semantic Linkbaks plugins?

**Comment by pfefferle** [comment]
Any news?

**Comment by chrisaldrich** [comment]
<a href="https://github.com/pfefferle/wordpress-webmention/issues/97#issuecomment-241784351" class="u-in-reply-to"></a>I've been following the conversation on https://github.com/pfefferle/wordpress-semantic-linkbacks/issues/71 which I think is closely related as it's primarily Facebook comments with emoji that seem to be causing the root problem.  

I'll spend some time in the next two days to see if i can stumble across the "fix" snarfed did and close this out. Thanks for the reminder @pfefferle.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/pfefferle/wordpress-webmention/issues/97#issuecomment-241784351" class="u-in-reply-to"></a>Still haven't found the solution, but I'm thinking it may be as a result of encoding on mySQL database. Cross reference https://wordpress.org/support/topic/wordpress-chokes-on-turkey-emoji-for-thanksgiving/ 

Closing for now...

**Comment by chrisaldrich** [comment]
<a href="https://github.com/pfefferle/wordpress-webmention/issues/97" class="u-in-reply-to"></a>I have a strong suspicion after some  that this was a result of the uf2 plugin and possibly the fact that it puts h-entry hentry on the main <body> tag which covers pretty much the entire page. Thus when other plugins were adding a class with "author" it was catching random https://brid-gy.appspot.com links from elsewhere on the page and throwing a wrench into the process.  Removing uf2 plugin seemed to remedy the issue.
