### ISSUE TITLE
not sending outbound webmentions at all?

### ISSUE THREAD

**Issue by snarfed** [pfefferle/wordpress-webmention#98]
it took me a bit to notice, but my site hasn't been sending outbound webmentions for months now. :( i don't know if upgrading the plugin broke it, or upgrading my wordpress, or something else entirely. i'm on WP 4.6, plugin version 3.0.0 (repo head as of this morning). plugin v2.6.0 also wasn't sending them.

@dshanske and i have been discussing a bit: https://chat.indieweb.org/dev/2016-09-02#t1472854670258000 . i'm opening this just to start tracking.  thanks for maintaining this plugin, @pfefferle et al!

**Comment by snarfed** [comment]
cc @singpolyma, @dshanske thinks you might have had the plugin send outbound wms ok since version 2.6.0 or later?

**Comment by pfefferle** [comment]
Hey snarfed, I had similar problems, some time ago... the problem for me was, that the wp-crons hang. I fixed with deleting all cron entries with a plugin and after doing so, it worked fine!

**Comment by pfefferle** [comment]
this is the plugin I used to clear the cron table...

**Comment by pfefferle** [comment]
oops ... her is the Link https://wordpress.org/plugins/advanced-cron-manager/

**Comment by dshanske** [comment]
I am checking through the code just in case .

**Comment by snarfed** [comment]
thanks @pfefferle! i installed that plugin and both executed (successfully) and removed all of the cron tasks it let me, but no luck. still not sending webmentions.

**Comment by pfefferle** [comment]
@snarfed the code seems to be fine, and I debugged it on a local machine without any findings. Have you changed anything else? added some plugins? is it only for a specific kind of posts? custom post types?

**Comment by pfefferle** [comment]
I also tested it on my live system with webmention.rocks and it worked fine too: https://webmention.rocks/test/1

**Comment by voxpelli** [comment]
Something along the lines of #89 would be helpful to know if cron is at all running or what it might be that errors out

**Comment by pfefferle** [comment]
I think I will add an option to choose between sending Webmentions directly instead of using the cron...

**Comment by dshanske** [comment]
@pfefferle, on a per post or global basis?

**Comment by dshanske** [comment]
I was thinking of a way to trigger all unsent Webmentions.

**Comment by voxpelli** [comment]
@dshanske That could turn into a very large job, so then one would at least need to limit it so that it takes a small enough chunk each time to finish within a reasonable time. (One could then go completely overkill with AJAX and autotrigger chunks one after another until all are done of course, but still).

I think @pfefferle are thinking that whenever a post is saved as part of that save the pings are done.

**Comment by dshanske** [comment]
@voxpelli Agree with you it could. Probably shouldn't. But I was just looking at that code section and even now, it could count the number of returned pending webmentions, only do 5, and then reschedule the rest.

**Comment by snarfed** [comment]
@pfefferle i think they haven't been sending on my site for months at least. all post types, afaict. no meaningful theme or plugin changes. i have been upgrading wordpress itself, i'm now on 4.6, but i expect you all are too. sorry i don't have any useful clues!

**Comment by dshanske** [comment]
There is a plugin called Post Meta Inspector. See if you have a meta flag called _mentionme in any of the unsent posts? That would mean the cron job never ran.

**Comment by snarfed** [comment]
yup! they do indeed have post meta `_mentionme = '1'`.

**Comment by pfefferle** [comment]
You can try to run the ping cron by hand using the `execute` button in the "Advanced Cron Manager".

**Comment by snarfed** [comment]
i don't see any cron jobs that that look webmention related. :( here's what i see:

```
jetpack_sync_cron
ngg_delete_expired_transients
jetpack_clean_nonces
wp_cache_gc
sucuriscan_scheduled_scan
wp_version_check
wp_update_plugins
wp_update_themes
wp_scheduled_delete
wp_scheduled_auto_draft_delete
jp_purge_transients_cron
jetpack_v2_heartbeat
akismet_scheduled_delete
```

**Comment by pfefferle** [comment]
ok, then this might be the problem...

**Comment by snarfed** [comment]
it's working again now! no clue what changed.

**Comment by pfefferle** [comment]
the cron system of wordpress seems not that stable...

**Comment by dshanske** [comment]
One of the ideas for Webmentions I want to support is someone who wants to run a separate process that can communicate with WordPress that verifies/sends webmentions.

**Comment by pfefferle** [comment]
You mean delegating WordPress Webmentions to another service?

**Comment by dshanske** [comment]
Parts of it. I don't want to build it, I want to have the right support there. Webmention.io is the inspiration for that.

**Comment by snarfed** [comment]
i take it back, this is still happening for me. i must have misinterpreted the one that i thought worked, or it was a fluke, or something.

**Comment by dshanske** [comment]
I have had this issue. There is something here, but still stumped as to what caused it. It may have been something outside the plugin, inside, or combination.

**Comment by pfefferle** [comment]
@snarfed have you rechecked your WP crons?

**Comment by snarfed** [comment]
@pfefferle same as last time. :/ wp_*, jetpack, others, but none for webmention.

**Comment by dshanske** [comment]
Wonder if #101 might help with the unknown.

**Comment by pfefferle** [comment]
do you have pings enabled for your blog?

**Comment by pfefferle** [comment]
webmentions don't have their own cron, they hook into the pingback/trackback crons

**Comment by snarfed** [comment]
> do you have pings enabled for your blog?

i think so! these, right?

<img width="839" alt="screen shot 2016-10-17 at 7 16 31 am" src="https://cloud.githubusercontent.com/assets/778068/19441208/b3c487f4-9439-11e6-885f-6b1be95e9499.png">

> webmentions don't have their own cron, they hook into the pingback/trackback crons

ah ok. here are the cron jobs i have. i don't see any that look like pingback or trackback...

```
akismet_scheduled_delete
jetpack_clean_nonces
jetpack_sync_cron
jetpack_sync_full_cron
jetpack_v2_heartbeat
jp_purge_transients_cron
ngg_delete_expired_transients
sucuriscan_scheduled_scan
wp_cache_gc
wp_scheduled_auto_draft_delete
wp_scheduled_delete
wp_update_plugins
wp_update_themes
wp_version_check
```

**Comment by snarfed** [comment]
i also checked and confirmed that i'm not overriding those settings for individual posts:

<img width="353" alt="screen shot 2016-10-17 at 7 21 38 am" src="https://cloud.githubusercontent.com/assets/778068/19441378/6c247354-943a-11e6-833c-c2a63f49470a.png">

**Comment by pfefferle** [comment]
This is not the correct place... This is the client part... the server part is on top of the page... something like "Attempt to notify any blogs linked to from the article"...

**Comment by pfefferle** [comment]
Sorry, haven't seen the first screenshot... hmmm seems ok so far...

**Comment by snarfed** [comment]
the webmention W3C spec is making progress, and @aaronpk et al [have been soliciting](https://chat.indieweb.org/2016-10-31#t1477948450433000) [implementation reports](https://github.com/w3c/webmention/tree/master/implementation-reports), and i started to look into doing one for wordpress...but stopped short when i realized i still have this bug. :/

**Comment by dshanske** [comment]
Are you on stable or development?

**Comment by snarfed** [comment]
@dshanske 3.0.0, repo head as of 9/2 when i filed this, as mentioned in the issue description.

[looking at the commits since then](https://github.com/pfefferle/wordpress-webmention/commits/master), i don't see anything that seems likely to fix this, but i'll definitely try pulling from head!

**Comment by dshanske** [comment]
Just wanted to eliminate possibilities.

**Comment by snarfed** [comment]
fwiw, i tried at both 64b11c43c2c6f4f003cc43ee8bc857c16056cfb9 (head) and e3573faea99ddafb9e0c322a9e19a9e8424421c8 (2.6.0), and had the same problem. no outgoing wms. :/

**Comment by snarfed** [comment]
same problem on my local instance, which is its own separate installation and config. so either it's some config setting or other conflict that's on both instances, or a bug. i'll start debugging.

**Comment by dshanske** [comment]
Personally, I'd like to solve this before we push to stable if we can.

**Comment by snarfed** [comment]
making some progress. my local instance has 7 posts with post meta key `_mentionme` and value `1`, but [this `get_posts` query](https://github.com/pfefferle/wordpress-webmention/blob/master/includes/class-webmention-sender.php#L170-L179) is returning an empty array of posts.

looks like `'meta_key' => '_mentionme'` is the problem. if i comment out all other args, it still returns nothing. if i comment out just the `meta_key` arg, it returns all posts. i don't understand _why_ it's a problem yet, though, seems ok [based on the wordpress docs](https://codex.wordpress.org/Class_Reference/WP_Query).

**Comment by snarfed** [comment]
tried adding `'meta_value' => '1'` and switching to `'meta_query' => array( array( 'key' => '_mentionme' ) )`. neither helped.

**Comment by dshanske** [comment]
We're sure the query is returning the post you updated?

**Comment by snarfed** [comment]
great nudge @dshanske, thanks! that helped me figure this out. you're right, removing `'key' => '_mentionme'` was a red herring. the query returned lots of posts without it, but still not the one i updated.

it looks like the bug is actually a bad interaction between `'publicly_queryable' => true` ([background on why it was added here](https://github.com/pfefferle/wordpress-webmention/issues/93#issuecomment-238027358)) and another plugin i use, [Ultimate Category Excluder](https://wordpress.org/plugins/ultimate-category-excluder/). when i use that plugin to exclude a category from the main page (which i do for my replies, likes, reposts, etc), they're also excluded from the `'publicly_queryable' => true` query, so webmentions aren't sent for them.

boo. :/ well, at least we found the problem! not sure how to fix it, but i'm guessing it won't be too hard.

**Comment by dshanske** [comment]
I handled that change. Let me explore the code.

**Comment by dshanske** [comment]
Try removing any arguments for get_post_types. It was supposed to save resources, but if you call it with no argument it will return all post types. pings_open is checked elsewhere so it will prevent oversending. If that works for you, we should put it in.

**Comment by snarfed** [comment]
i wish it was that easy! unfortunately Ultimate Category Excluder filters `get_posts` and adds its own conditions to filter out posts in some cases, which evidently also catches this `get_posts` call.

here's that code: https://plugins.trac.wordpress.org/browser/ultimate-category-excluder/trunk/ultimate-category-excluder.php#L141

so, i have to figure out how to tweak wordpress-webmention's `get_posts` call so it still works but doesn't trigger Ultimate Category Excluder. whee.

**Comment by dshanske** [comment]
But is that something the plugin should account for? Basically, is it a blocker for other people?

**Comment by snarfed** [comment]
sent a PR (#105) that fixes this for users with Ultimate Category Excluder installed, and has no effect on other users. special cases are annoying and not ideal, but i couldn't think of a better approach. open to other ideas!

**Comment by pfefferle** [comment]
@snarfed do you think this is valid for everyone using the combination of these two plugins?

Do you think it is a better idea to make the `get_posts` args filterable?

**Comment by snarfed** [comment]
i think this is the right approach. UCE doesn't make posts private, it just lets you omit them in certain places - home page, search results, etc. users still want them visible in other places, or they would have made them private or drafts.

since they're still intended to be visible in some places, sending wms for them makes sense to me.

you're right, we could instead filter `get_posts` and remove UCE's changes. this is equivalent, and seems safer and cleaner, but I'm ok with either way.

**Comment by dshanske** [comment]
I don't have an objection to putting in this edge case if it solves the problem. There seems to be no way to override the filter otherwise.
